sap-linuxlab/community.sap_install

- .github/workflows/ansible-lint sap_general_preconfigure.yml
- .github/workflows/ansible-lint sap_hana_install.yml
- .github/workflows/ansible-lint sap_hana_preconfigure.yml
- .github/workflows/ansible-lint sap_netweaver_preconfigure.yml
- .github/workflows/ansible-test-sanity.yml
- README.md
- requirements-dev.txt
- roles/sap_general_preconfigure/README.md
Currently there is only one ansible lint workflow for some roles. With this changes several separate workflows are introduced to have one workflow for one role. 
Table with workflow status is added to README.md. Move it as you like, if not correct place.
> Separate ansible lint workflows for some roles 

- .github/workflows/ansible-lint sap_general_preconfigure.yml
- .github/workflows/ansible-lint sap_hana_install.yml
- .github/workflows/ansible-lint sap_hana_preconfigure.yml
- .github/workflows/ansible-lint sap_netweaver_preconfigure.yml
- .github/workflows/ansible-lint.yml
- roles/sap_hana_install/README.md
- roles/sap_hana_install/defaults/main.yml
- roles/sap_hana_install/tasks/assert-addhosts-loop-block.yml
- roles/sap_hana_install/tasks/hana_addhosts.yml
- roles/sap_hana_install/tasks/hana_exists.yml
- roles/sap_hana_install/tasks/hana_install.yml
- roles/sap_hana_install/tasks/post_install.yml
- roles/sap_hana_install/tasks/pre_install.yml
- roles/sap_hana_install/tasks/pre_install/extract_sar.yml
- roles/sap_hana_install/tasks/pre_install/hdblcm_prepare.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/disable-services.yml
This is mainly a rework of the pre_install part, allowing greater flexibility and avoiding some pitfalls:
- We select the directory in which the file hdblcm is located by searching for this file instead of searching for directory SAP_HANA_DATABASE (#29).
- The role now detects the correct SAPCAR EXE file and selects the latest version found, to support one or more SAPCAR EXE files in the software directory. Alternatively, the file name of the SAPCAR EXE file can be set with a variable (#32).
- The role will abort if a user group exists with a different group ID than specified in variable sap_hana_install_groupid (#33).
- The HANA software extraction directory can be set to a different location than ./extracted below the software directory (#36).
- If the role is executed on more than one …
> sap_hana_install: Solve issues #29, #32, #33, #36, #37, #39, and #40

- roles/sap_general_preconfigure/tasks/RedHat/generic/assert-selinux.yml
- roles/sap_general_preconfigure/tasks/RedHat/generic/configure-selinux.yml
- roles/sap_general_preconfigure/tasks/RedHat/installation.yml
- roles/sap_general_preconfigure/tests/sap_general_preconfigure-default-settings.yml
- roles/sap_hana_install/README.md
- roles/sap_hana_install/defaults/main.yml
- roles/sap_hana_install/tasks/assert-addhosts-loop-block.yml
- roles/sap_hana_install/tasks/hana_addhosts.yml
- roles/sap_hana_install/tasks/hana_exists.yml
- roles/sap_hana_install/tasks/main.yml
- roles/sap_hana_install/tasks/post_install.yml
- roles/sap_hana_install/tasks/post_install/hdbuserstore.yml
- roles/sap_hana_install/tasks/post_install/log_mode.yml
- roles/sap_hana_install/tasks/pre_install.yml
- roles/sap_hana_install/tasks/pre_install/extract_sar.yml
- roles/sap_hana_install/tasks/pre_install/hdblcm_prepare.yml
- roles/sap_hana_preconfigure/README.md
- roles/sap_hana_preconfigure/defaults/main.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-tuned.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/configure-tuned.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/disable-ksm.yml
- roles/sap_hana_preconfigure/tasks/sapnote/2777782/02-configure-tuned.yml
- roles/sap_hana_preconfigure/tests/sap_hana_preconfigure-default-settings.yml
- roles/sap_hana_preconfigure/vars/main.yml
- roles/sap_netweaver_preconfigure/tests/sap_netweaver_preconfigure-default-settings.yml
This pull request contains two separate modifications:
- sap_hana_preconfigure now supports a custom tuned profile, set in new variable `sap_hana_preconfigure_tuned_profile`. If the variable is not set, the default tuned profile 'sap-hana' will be used (issue #43).
- sap_hana_install now supports checksum verification for the SAPCAR executable and the SAR files in the software directory (either specified in role variables `sap_hana_install_sapcar_filename` and/or `sap_hana_install_sarfiles_list` or found by the role) for which a file named `FILE.sha256sum` exists in the same directory, where `FILE` is the name of the SAPCAR executable or SAR file (issue #44).
> sap_hana_preconfigure: Support for custom tuned profile; sap_hana_install: Support for checksum verification

- roles/sap_hana_install/README.md
- roles/sap_hana_install/defaults/main.yml
- roles/sap_hana_install/tasks/pre_install/extract_sar.yml
These patches implement the feature described in Issue #53 and fixed a documentation bug.
> sap-hana-install: New feature: Copy SAR files before extracting

- roles/sap_general_preconfigure/tasks/RedHat/assert-installation.yml
- roles/sap_general_preconfigure/tests/run-sap_general_preconfigure-tests-s390x.py
- roles/sap_general_preconfigure/tests/run-sap_general_preconfigure-tests.py
- roles/sap_general_preconfigure/tools/beautify-assert-output.sh
- roles/sap_hana_install/defaults/main.yml
- roles/sap_hana_install/tasks/pre_install/hdblcm_configfile.yml
- roles/sap_hana_install/templates/configfile.j2
- roles/sap_hana_install/templates/sap-nw-input.j2
- roles/sap_hana_preconfigure/tests/run-sap_hana_preconfigure-tests.py
- roles/sap_hana_preconfigure/tools/beautify-assert-output.sh
- roles/sap_netweaver_preconfigure/tests/run-sap_netweaver_preconfigure-tests.py
- roles/sap_netweaver_preconfigure/tools/beautify-assert-output.sh
The hdblcm --dump_configfile_template command already puts a default
into the `hostname` parameter, so the corresponding variable in
defaults/main.yml needs to be commented out.
For other hdblcm parameters in defaults/main.yml, additional comments
should assist in determining the relationship between the role variables
and the hdblcm parameters. Future releases could remove all deviating
role variables in favor of just using the hdblcm parameter names
prepended by the name of the role and an underscore.
Examples:
hdblcm parameter: org_manager_user
Current role variable: sap_hana_install_xs_org_user
Matching role variable: sap_hana_install_org_manager_user
hdblcm parameter: lss_userid
Current role variable: sap_hana_install_lss_user
Matching role variable: sap_hana_install_lss_userid
> sap_hana_install: Modify and describe defaults in defaults/main.yml

- roles/sap_hana_install/tasks/pre_install/prepare_sapcar.yml
- roles/sap_swpm/tasks/pre_install/update_etchosts.yml
if sapcar is in a different directory than the IMDB* file, it cannot be used. 
Hence I added "| basename" to the variable where the exact filename is needed. This doesn't change the behavior, but enables me to specify sap_hana_install_sapcar_filename relative to the HANA software directory. 
EXAMPLE:
```
#------------------
sap_hana_install_software_directory: /software/HANA_installation
sap_hana_install_sapcar_filename: ../SAPCAR/SAPCAR_1311-80000935.EXE
sap_hana_install_common_master_password: "R3dh4t$123"
sap_hana_install_sid: 'RHE'
sap_hana_install_instance_number: "00"
```
It is tested and works
> sap_hana_install: quickfix 

- roles/sap_hana_install/tasks/pre_install/prepare_sapcar.yml
- roles/sap_swpm/tasks/pre_install/update_etchosts.yml
Note: ansible-lint 5.4.0 using ansible 2.12.2 completed manually for the sap*preconfigure and sap_hana_install roles.
> sap_hana_install: back out changes of PR #90

- roles/sap_hana_install/tasks/post_install/hdbuserstore.yml
- roles/sap_hana_preconfigure/tasks/sapnote/1944799/installation.yml
- roles/sap_hana_preconfigure/tasks/sapnote/2578899/installation.yml
- roles/sap_hana_preconfigure/tasks/sapnote/2684254/installation.yml
The hana pre configure role fails because of package name changes
> SLES fix package upgrade

- roles/sap_swpm/requirements.yml
- roles/sap_swpm/tasks/swpm.yml
But use the FQCN
Reason for going back to the pids module: Tests with calling the role from Terraform lead to a failed sapinst exit detection.
> sap_swpm: revert to pids module

- roles/sap_general_preconfigure/tasks/main.yml
- roles/sap_hana_preconfigure/tasks/main.yml
Notes:
- We flush the handlers at the end of roles sap_general_preconfigure and sap_hana_preconfigure, for maximum flexibility.
- We do not flush the handlers at the end of role sap_netweaver_preconfigure because the handlers/main.yml file is empty.
Solves issue #145.
Note: With the following parameter settings, only one reboot will be performed, at the end of role sap_hana_preconfigure:
```
sap_general_preconfigure_reboot_ok: no
sap_general_preconfigure_fail_if_reboot_required: no
sap_hana_preconfigure_reboot_ok: yes
sap_hana_preconfigure_fail_if_reboot_required: no
```
> sap*preconfigure: flush handlers at the end

- roles/sap_hana_install/defaults/main.yml
Reasons:
- "global variables" sap_hana_sid and sap_hana_install_number are already used for setting the corresponding role variables which start with `sap_hana_install_` , in tasks/main.yml.
- If the variable sap_hana_instance_number is not set, the role aborts in task "Rename some variables used by hdblcm configfile" but not in task "Fail if necessary variable 'sap_hana_install_number' is not configured" . The role even would abort in tasks/main.yml if just a debug task is attempting to display the variable `sap_hana_install_number` right at the beginning.
> sap_hana_install: Revert to empty sid and number vars in defaults/main.yml

- roles/sap_general_preconfigure/tasks/main.yml
- roles/sap_hana_preconfigure/tasks/main.yml
so that we have the correct status before we start the configuration. Solves issue https://github.com/sap-linuxlab/community.sap_install/issues/176 .
> preconfigure: Add package_facts after the installation phase

- roles/sap_ha_prepare_pacemaker/tasks/main.yml
Same improvement as in role sap_ha_install_hana_hsr, merged yesterday:
https://github.com/sap-linuxlab/community.sap_install/commit/6fe126bc348efb9aff7794e7eaed7946b6d42ce0
The `ignore_errors` are required for correct error handling in combination with `any_errors_fatal`.
> sap_ha_prepare_pacemaker: ignore_errors for connectivity checkers

- roles/sap_ha_install_hana_hsr/.ansible-lint
- roles/sap_ha_install_hana_hsr/.yamllint.yml
- roles/sap_ha_install_hana_hsr/tasks/hdbuserstore.yml
- roles/sap_ha_install_hana_hsr/tasks/pki_files.yml
- roles/sap_ha_install_hana_hsr/tasks/update_etchosts.yml
- roles/sap_ha_install_pacemaker/.ansible-lint
- roles/sap_ha_install_pacemaker/.yamllint.yml
- roles/sap_ha_prepare_pacemaker/.ansible-lint
- roles/sap_ha_prepare_pacemaker/.yamllint.yml
- roles/sap_ha_set_hana/.ansible-lint
- roles/sap_ha_set_hana/.yamllint.yml
**sap_ha_install_hana_hsr**
- PKI file copy via rsync not working when size and mtime of source and destination are identical
-> added `--checksum` for more reliable file comparison
-> added `-vv` for more output and parsing as `changed_when` indicator
**HA roles**
- missing role based ansible-lint and yamllint config files leads to more errors/warnings based on linter defaults
-> symlinks to repo parent created for a consistent linter config in all roles
> [HSR] PKI filersync fix and [HA roles] linter config symlinks

- roles/sap_ha_install_hana_hsr/tasks/configure_hsr.yml
- roles/sap_ha_install_hana_hsr/tasks/hdbuserstore.yml
- roles/sap_ha_install_hana_hsr/tasks/log_mode.yml
- roles/sap_ha_install_hana_hsr/tasks/main.yml
- roles/sap_ha_install_hana_hsr/tasks/update_etchosts.yml
I started to implement the first fixes for sap_ha_install_hana_hsr to work in the lab environment
The most important fixes are:
- accepts now fqdn instead of short name for hsr interface
- proper check if full qualified domain name is given instead of short
- proper check if short name exists as substring in other names (not fully tested)
- check if hsr interface is configured
- creates internal variable with proper part of sap_hana_cluster_nodes dict
Not fixed:
- can't define HSR interface on an interface that has the same short name like the primary. This will make a wrong entry to /etc/hosts. Identical short hostnames with different domains on different interfaces will create duplicate host entry for short name
Role tested against RH445 environment
> Dev: sap_ha_install_hana_hsr: Doesn't work with multiple interfaces #181

- roles/sap_ha_install_hana_hsr/tasks/configure_hsr.yml
- roles/sap_ha_install_hana_hsr/tasks/hdbuserstore.yml
- roles/sap_ha_install_hana_hsr/tasks/log_mode.yml
- roles/sap_ha_install_hana_hsr/tasks/main.yml
- roles/sap_ha_install_hana_hsr/tasks/pki_files.yml
- roles/sap_ha_install_hana_hsr/tasks/run_backup.yml
- roles/sap_ha_install_hana_hsr/tasks/update_etchosts.yml
- roles/sap_ha_install_pacemaker/tasks/cluster_setup.yml
- roles/sap_ha_install_pacemaker/tasks/main.yml
- roles/sap_ha_install_pacemaker/tasks/stonith_config.yml
- roles/sap_ha_prepare_pacemaker/tasks/main.yml
- roles/sap_ha_prepare_pacemaker/tasks/software_setup.yml
- roles/sap_ha_set_hana/tasks/cluster_constraint.yml
- roles/sap_ha_set_hana/tasks/cluster_resources.yml
- roles/sap_ha_set_hana/tasks/cluster_srhook.yml
- adjustments to fix ansible-lint issues
- new: backup files are verified via `hdbbackupcheck`
- https://github.com/sap-linuxlab/community.sap_install/issues/162
- adjustments to fix ansible-lint issues
- added `--enable --start --wait=30` to cluster setup command and removed separate start task
- disabled task for live update of quorum `expected-votes` - questioning/clarifying the actual need for this during provisioning
- new: check if all defined nodes are shown online after cluster setup
- new: failure conditional for stonith resource, because the command actually returns rc=0 even when it failed (e.g. for missing resource parameters)
- adjustments to fix ansible-lint issues
- added `__` prefix to internal role variable
> HA roles: linter fixes + new checks

- roles/sap_general_preconfigure/vars/SLES_15.yml
Fix for issue https://github.com/sap-linuxlab/community.sap_install/issues/218.
This defines the following empty variables in `roles/sap_general_preconfigure/vars/SLES_15.yml`
* __sap_general_preconfigure_packagegroups:
* __sap_general_preconfigure_envgroups:
* __sap_general_preconfigure_kernel_parameters_default: 
Without these variables defined the role fails.
> Fixed failing SLES15 preconfigure

- roles/sap_ha_pacemaker_cluster/README.md
- roles/sap_ha_pacemaker_cluster/meta/argument_specs.yml
Tiny adjustment to the `ha_cluster` argument definition (native `ha_cluster` role parameter) to  allow any option instead of a limited set.
> sap_ha_pacemaker_cluster: update argument def ha_cluster

- roles/sap_ha_pacemaker_cluster/defaults/main.yml
- roles/sap_ha_pacemaker_cluster/tasks/main.yml
**Fix 1**
The task creating the ha_cluster role compatible config vars file (for config review or re-use) is now only created when the user enables this var file creation. It was disabled by default for security reasons, but the conditional in the file creation task was missing.
**Fix 2**
The cluster name role variable now inherits the `ha_cluster` role variable for setting the cluster name, and only applies a default string if none of the 2 possible cluster name parameters is defined by the user.
> sap_ha_pacemaker_cluster: 2 small logic fixes

- requirements.yml
- roles/sap_ha_pacemaker_cluster/defaults/main.yml
- roles/sap_ha_pacemaker_cluster/tasks/main.yml
'latest' is not a valid version key for galaxy collections and causes dependency resolutions to fail during checks.
Version syntax reference: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#collections-older-version
Added a valid minimum version. This minimum is required for the ha_cluster role.
> Fix invalid collection version

- .pre-commit-config.yaml
- docs/getting_started/sample-playbook_deploy-2-node-sap-hana-cluster.yml
- roles/sap_ha_pacemaker_cluster/tasks/main.yml
**Cluster role and sample playbook**
The sample playbook for a 2-node SAP HANA cluster has been updated to use the new `sap_ha_pacemaker_cluster` role and the adjusted input variables.
**pre-commit**
Updated version v4.0.1 -> v4.3.0.
> sap_ha_pacemaker_cluster: updated 2-node cluster sample playbook

- roles/sap_hana_install/README.md
- roles/sap_hana_install/defaults/main.yml
- roles/sap_hana_install/tasks/post_install.yml
Requesting review from Markus Koch. Discussed with him
This PR is required to remove the extracted left overs of the SAP Install media on the node. When using with NFS Install media, the installation fails due to issue #188 so we had to define sap_hana_install_software_extract_directory. Noticed that the extracted files were not getting cleared after the SAP HANA install
> sap_hana_install: installation media handling actions when using NFS share

- roles/sap_swpm/tasks/main.yml
- roles/sap_swpm/tasks/pre_install.yml
- roles/sap_swpm/tasks/pre_install/install_type.yml
- roles/sap_swpm/tasks/swpm/swpm_inifile_generate_advanced.yml
- roles/sap_swpm/tasks/swpm/swpm_inifile_generate_advanced_templates.yml
- roles/sap_swpm/tasks/swpm/swpm_inifile_generate_default.yml
- roles/sap_swpm/tasks/swpm/swpm_inifile_generate_default_templates.yml
- roles/sap_swpm/tasks/swpm/swpm_inifile_generate_inifile_reuse.yml
- roles/sap_swpm/tasks/swpm/swpm_pre_install.yml
Add some tags to allow for easily executing only certain steps of the role:
- sap_swpm_pre_install: Only run all preinstallation steps
- sap_swpm_generate_inifile: Only generate the SWPM inifile
- sap_swpm_sapinst_commandline: Only display the full sapinst command line
- sap_swpm_install: Run all preinstallation and installation steps but omit the postinstallation steps
> sap_swpm: Add some tags (issue 281)

- roles/sap_general_preconfigure/tasks/RedHat/installation.yml
Tested with several RHEL 8.1...9.1 versions, on x86_64, ppc64le, and s390x. All systems booted successfully and had the Server software environment group installed afterwards.
> Solve issue 306 (avoid the `nobest` parameter in the `dnf` module)

- roles/sap_general_preconfigure/tasks/RedHat/generic/assert-etc-hosts.yml
Solves issue #332.
Proof:
```
192.168.0.1 space.domain host
192.168.0.2     tab.domain      tab
0000000   1   9   2   .   1   6   8   .   0   .   1       s   p   a   c
0000020   e   .   d   o   m   a   i   n       h   o   s   t  \n   1   9
0000040   2   .   1   6   8   .   0   .   2  \t   t   a   b   .   d   o
0000060   m   a   i   n  \t   t   a   b  \n
0000071
192.168.0.1 space.domain host
1
192.168.0.2     tab.domain      tab
1
```
The original code only checked for spaces whereas the new code checks for white spaces.
As per `man awk` in RHEL 8:
```
\s         Matches any whitespace character.
```
An alternative solution would be to specify the character class `[[:space:]]`:
```
192.168.0.1 space.domain host
1
192.168.0.2     tab.domain      tab
1
```
but this should not be necessary …
> sap_general_preconfigure: recognize tabs in /etc/hosts

- roles/sap_netweaver_preconfigure/README.md
- roles/sap_netweaver_preconfigure/defaults/main.yml
- roles/sap_netweaver_preconfigure/meta/argument_specs.yml
- roles/sap_netweaver_preconfigure/vars/RedHat_7.yml
- roles/sap_netweaver_preconfigure/vars/RedHat_8.yml
- roles/sap_netweaver_preconfigure/vars/RedHat_9.yml
- roles/sap_netweaver_preconfigure/vars/SLES_15.yml
At the same time, remove OS dependent vars where possible (`sap_netweaver_preconfigure_min_swap_space_mb` in this case).
Solves issue https://github.com/sap-linuxlab/community.sap_install/issues/321.
The role's file README.md will be updated as the next step.
> sap_netweaver_preconfigure: Use meta/argument_specs.yml

- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_stonith.yml
**Before**
Any custom stonith resources definition list of more than 1 element would result in only the last stonith resource being created due to the resource variable being overwritten, instead of appended to.
**After**
The elements in the custom stonith definition list are appended correctly to a list of resources to be configured.
All defined resources are now actually configured in the cluster.
> sap_ha_pacemaker_cluster: fixed custom stonith resources list of >1 elements

- .github/workflows/ansible-lint-sap_ha_pacemaker_cluster.yml
Newly released ansible-compat version appears not compatible with ansible-lint versions <6.12.2 on python 3.9.
Working around by installing the previous working version of ansible-compat, 3.0.2.
> gh action - workaround for compatibility with older ansible-lint

- .github/workflows/ansible-lint-sap_general_preconfigure.yml
- .github/workflows/ansible-lint-sap_ha_install_hana_hsr.yml
- .github/workflows/ansible-lint-sap_hana_install.yml
- .github/workflows/ansible-lint-sap_hana_preconfigure.yml
- .github/workflows/ansible-lint-sap_hypervisor_node_preconfigure.yml
- .github/workflows/ansible-lint-sap_netweaver_preconfigure.yml
- .github/workflows/ansible-lint-sap_swpm.yml
- .github/workflows/ansible-lint-sap_vm_preconfigure.yml
- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-test-sanity.yml
2 days ago ansible-compat version 4.0.1 has been released. This version is automatically installed by the ansible-lint dependencies, but does not seem to be compatible with ansible-lint versions <6.12.2.
In order to keep 6.8.6 ansible-lint for the time being, this update of the workflows makes sure that ansible-compat version 3.0.2 is explicitly installed.
Tested here:
https://github.com/ja9fuchs/community.sap_install/actions/runs/4874282848/jobs/8695013042
> gh actions: install fixed ansible-compat version to keep compatibility

- roles/sap_ha_pacemaker_cluster/README.md
- roles/sap_ha_pacemaker_cluster/meta/argument_specs.yml
For a dict that can be enhanced with custom key-value pairs, `options:` can not be used to explain the default options, because the arguments validation will not allow additional options other than those defined explicitly.
This change removes the `options:` section from the parameter specification of `sap_ha_pacemaker_cluster_fence_options` (including updated rebuild of the arguments README section).
> sap_ha_pacemaker_cluster: fix issue #370 - argument_specs limitation

- roles/sap_storage_setup/tasks/generic_tasks/configure_nfs_filesystems.yml
- roles/sap_storage_setup/tasks/main.yml
NFS handling for individual fs parameters was not working as expected and always failed back to using global variables instead.
Now the definition is resolved in the correct format and individual settings applied correctly.
The parameter `sap_storage_setup_host_role` has been renamed to `sap_storage_setup_host_purpose`.
> sap_storage_setup: fixes in NFS task logic and parameter rename

- .github/workflows/ansible-lint-sap_general_preconfigure.yml
- .github/workflows/ansible-lint-sap_ha_install_hana_hsr.yml
- .github/workflows/ansible-lint-sap_hana_install.yml
- .github/workflows/ansible-lint-sap_hana_preconfigure.yml
- .github/workflows/ansible-lint-sap_hypervisor_node_preconfigure.yml
- .github/workflows/ansible-lint-sap_netweaver_preconfigure.yml
- .github/workflows/ansible-lint-sap_storage_setup.yml
- .github/workflows/ansible-lint-sap_swpm.yml
- .github/workflows/ansible-lint-sap_vm_preconfigure.yml
- .github/workflows/ansible-lint.yml
Locking the Ansible environment to the following versions, in order to keep the dependencies compatible with our locked ansible-lint version.
```
Package                 Version
----------------------- ---------
ansible                 7.5.0
ansible-compat          3.0.2
ansible-core            2.14.5
ansible-lint            6.8.6
```
> workflows: version locking of ansible packages for compatibility

- roles/sap_hana_install/defaults/main.yml
- roles/sap_hana_install/tasks/post_install/log_mode.yml
This change:
- sets `log_mode` to `overwrite` only if the new role parameter `sap_hana_install_log_mode` is set to `overwrite`
- sets `log_mode` to `overwrite` only for the initial tenant database if `sap_hana_install_create_initial_tenant` had been set to `y`.
> sap_hana_install: Solve issue #213

- roles/sap_general_preconfigure/README.md
- roles/sap_general_preconfigure/defaults/main.yml
- roles/sap_general_preconfigure/meta/argument_specs.yml
- roles/sap_general_preconfigure/tasks/RedHat/assert-installation.yml
- roles/sap_general_preconfigure/tasks/RedHat/installation.yml
- roles/sap_general_preconfigure/vars/RedHat_7.yml
- roles/sap_general_preconfigure/vars/RedHat_8.0.yml
- roles/sap_general_preconfigure/vars/RedHat_8.1.yml
- roles/sap_general_preconfigure/vars/RedHat_8.2.yml
- roles/sap_general_preconfigure/vars/RedHat_8.yml
- roles/sap_general_preconfigure/vars/RedHat_9.yml
- roles/sap_hana_preconfigure/tasks/RedHat/assert-installation.yml
- roles/sap_hana_preconfigure/vars/RedHat_8.yml
- roles/sap_hana_preconfigure/vars/RedHat_9.yml
As per SAP note https://me.sap.com/notes/2679703, version 4, the ibm-power-managed-rhelX package has to be installed on ppc64le for all SAP HANA and NetWeaver/ABAP application server systems, for RHEL 8 and 9.
This PR replaces the list of individual packages by `ibm-power-managed-rhelX` in role `sap_hana_preconfigure` (so the interface does not change), and enables the installation and installation assertion of these packages in the role `sap_general_preconfigure`.
> sap_general_preconfigure, sap_hana_preconfigure: Install the ibm-power-managed-rhelX package

- roles/sap_ha_pacemaker_cluster/README.md
A few adjustments were made to sync the README with previous argument specs changes.
A "Tips" sections has been added with a link to the `ha_cluster` LSR README for additional parameters and the suggestion of issue #364 used as example.
> sap_ha_pacemaker_cluster: README update

- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_stonith.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/include_vars_platform.yml
This fix is required for the role to work for not explicitly discovered platforms (like ovirt).
**edit**
Additional fix to disable STONITH when there is no stonith resource defined.
If stonith is enabled with no fencing resource configured, it will prevent other resources from starting.
> sap_ha_pacemaker_cluster: fix missing value in platform task conditional

- roles/sap_install_media_detect/defaults/main.yml
- roles/sap_install_media_detect/tasks/detect_export_sapecc.yml
- roles/sap_install_media_detect/tasks/detect_export_sapecc_ides.yml
- roles/sap_install_media_detect/tasks/detect_export_sapnwas_abap.yml
- roles/sap_install_media_detect/tasks/detect_export_sapnwas_java.yml
- roles/sap_install_media_detect/tasks/detect_export_sapsolman_abap.yml
- roles/sap_install_media_detect/tasks/detect_sapanydb_ibmdb2.yml
- roles/sap_install_media_detect/tasks/detect_sapanydb_oracledb.yml
- roles/sap_install_media_detect/tasks/detect_sapanydb_sapase.yml
- roles/sap_install_media_detect/tasks/detect_sapanydb_sapmaxdb.yml
- roles/sap_install_media_detect/tasks/prepare/enable_rar_handling.yml
- add ` -o` as an additional option to the `unar` command for specifying the destination extraction directory 
- remove all of `set -o pipefail` for all shell command sequences which contain `grep -q`
- add ` # noqa risky-shell-pipe` to the affected tasks and add `Reason for noqa: ...` in a comment right before the task
> Solve issue 426

- roles/sap_install_media_detect/defaults/main.yml
- roles/sap_install_media_detect/tasks/detect_export_sapecc.yml
- roles/sap_install_media_detect/tasks/detect_export_sapecc_ides.yml
- roles/sap_install_media_detect/tasks/detect_export_sapnwas_abap.yml
- roles/sap_install_media_detect/tasks/detect_export_sapnwas_java.yml
- roles/sap_install_media_detect/tasks/detect_export_sapsolman_abap.yml
- roles/sap_install_media_detect/tasks/detect_sapanydb_ibmdb2.yml
- roles/sap_install_media_detect/tasks/detect_sapanydb_oracledb.yml
- roles/sap_install_media_detect/tasks/detect_sapanydb_sapase.yml
- roles/sap_install_media_detect/tasks/detect_sapanydb_sapmaxdb.yml
- roles/sap_install_media_detect/tasks/set_global_vars.yml
Successfully tested `sap_install_media_detect` (but not the actual SWPM installation) with various combinations of existing and nonexisting `*_extracted` directories and different settings of `sap_install_media_detect_skip_extraction_if_destination_dir_exists` for:
- sap_nwas_abap_hana
- sap_nwas_abap_ibmdb2
> Solve issue #428

- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_stonith.yml
- roles/sap_ha_pacemaker_cluster/tasks/main.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/include_vars_platform.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_aws_ec2_vs.yml
**Fixes of stonith resource configuration:**
- line break in pcmk_host_map variables caused fencing not working
- commented out AWS credentials from default stonith definition, it will automatically use the aws cli credentials that are configured anyway for the VIP resource
- cosmetical fix of a duplicate pattern in the resource name
**Added:**
AWS cloud-init services are disabled and stopped.
--> Required to avoid removal of the floating Overlay IP.
> sap_ha_pacemaker_cluster: AWS improvements

- roles/sap_swpm/tasks/post_install.yml
A new Ansible Task to update the hdbuserstore to update the hostname insead of IP address correctly
Problem arises when communication between NWAS VM and HANA DB VM must happen over dedicated/different subnet (IP address) than the SAP HANA DB host's primary subnet/IP address.
For example `hdbuserstore SET DEFAULT <dbhost>:30215 SAPBS4 Perf0rm` where dbhost can be IP address or hostname.
Current behaviour:
- HANA LPAR has 3 networks attached to it.
- 10.51.0.x (management subnet),
- 10.52.0.x (backup subnet)
- 10.53.0.x (sap subnet)
- Communication/traffic must flow between nw and HANA host using 10.53.0.x sap subnet
- Even though passing 10.53.0.x IP to `sap_swpm_db_ip` during installation somehow the SAP SWPM installation retrieves the management IP of HANA LPAR 10.51.0.x(management …
> sap_swpm: fix post-execution update of the hdbuserstore with correct host name

- roles/sap_ha_pacemaker_cluster/tasks/platform/construct_vars_vip_resources_cloud_gcp_ce_vm.yml
In Google cloud platform the primary instance IP is by default /32 and the VIP must also be /32 to avoid conflicts with the routing.
Adding the cidr_netmask to the IPaddr2 resources with a hard-coded value of 32 for the time being, until further detection functionality has been added to make this dynamic for all platforms.
> sap_ha_pacemaker_cluster: fix: GCP vip resource force cidr 32

- roles/sap_ha_pacemaker_cluster/defaults/main.yml
- roles/sap_ha_pacemaker_cluster/tasks/include_construct_vip_resources.yml
- strip the (optional) /xx cidr suffix from the IP address parameters
- IP address parameters combined for configuration must correspond to the individual host's host type - this is needed to support defining e.g. HANA and NetWeaver IP parameters in the same config file, but avoid VIP resources to be configured in the wrong cluster
> sap_ha_pacemaker_cluster: fixes to the VIP address parameters

- playbooks/vars/sample-variables-sap-swpm-default-mode-solman-hana-abap-onehost-install.yml
- playbooks/vars/sample-variables-sap-swpm-default-mode-solman-hana-java-onehost-install.yml
- roles/sap_install_media_detect/defaults/main.yml
- roles/sap_install_media_detect/tasks/organize_files.yml
- roles/sap_install_media_detect/tasks/prepare/create_file_list_phase_2.yml
- roles/sap_install_media_detect/tasks/set_global_vars.yml
- roles/sap_swpm/defaults/main.yml
- roles/sap_swpm/templates/configfile.j2
- fix for incorrect handling of `SIGNATURE.SMF` for HANA SAR files in role `sap_install_media_detect`
- variable name change from `sap_swpm_cd_rdms_path` to `sap_swpm_cd_rdbms_path` in all affected places in the collection
- file `sap_install_media_detect/defaults/main.yml` now with two different variable settings, one for SAP S/4HANA and one for SAP ERP 6.0 EHP8 with SAP HANA database, the former one active (= not commented out)
> Issue 385 new detection method - bug fixes

- roles/sap_install_media_detect/README.md
- roles/sap_install_media_detect/defaults/main.yml
- roles/sap_install_media_detect/tasks/find_files_after_extraction.yml
- roles/sap_install_media_detect/tasks/main.yml
- roles/sap_install_media_detect/tasks/organize_files.yml
- roles/sap_install_media_detect/tasks/prepare/check_directories.yml
- roles/sap_install_media_detect/tasks/prepare/create_file_list_phase_2.yml
- roles/sap_install_media_detect/tasks/prepare/enable_zip_handling.yml
- roles/sap_install_media_detect/tasks/set_global_vars.yml
This PR contains the following changes:
- set all SAP product related vars in `defaults/main.yml` to empty or, in case of boolean, to false
- no longer set vars to defaults in comparisons (because all vars are already set in `defaults/main.yml`)
- add more DB client file handling code, to support cases where only the DB client files are needed and not all the DB installation files
- use different variable names of `sap_swpm_kernel_dependent_file_name_get` for db unspecific and for db specific cases
- ensure the unzip package is present so the `sapfile` utility will work even on systems where the `sap*preconfigure` roles have not been executed before
- replace double quotes by single quotes in string comparisons
> Issue 385 new detection method - further changes

- roles/sap_swpm/tasks/swpm/detect_variables.yml
This PR contains the following improvements:
- The variable `sap_swpm_inifile_product_id_detect` will be detected correctly from one of the following lines in inifile.params:
```
```
or
```
```
If both lines are present, the first occurrence will be used.
- The variables `archives.downloadBasket`, `NW_GetSidNoProfiles.sid` and `NW_getFQDN.FQDN` are now determined only from lines which do not start with `#  `.
- The Ansible `shell` module is no longer required. The `command` module is sufficient because we do no longer need pipes.
- The task titles now all start with `SAP SWPM - `.
> sap_swpm: Improve the detection of variables in inifile.params

- roles/sap_install_media_detect/tasks/organize_files.yml
Solves issue #470 - found no deviation for any SAPCAR file which are to be extracted, with the exception of the SAP ASE client which now is handled properly by the role.
I also added two comments which explain why we handle SAPCAR file extraction differently for different types of SAPCAR files.
> sap_install_media_detect: Fix SAPCAR extraction error for SAP ASE Client

- roles/sap_general_preconfigure/README.md
- roles/sap_general_preconfigure/defaults/main.yml
- roles/sap_general_preconfigure/meta/argument_specs.yml
- roles/sap_general_preconfigure/tasks/RedHat/configuration.yml
- roles/sap_general_preconfigure/tasks/RedHat/generic/configure-selinux.yml
- Fixes #464: Allow more directories than just `/usr/sap` to be created and SELinux labeled
- Also fixes #355. The role will now skip calling the `lsr/selinux` role if the current SELinux state is `disabled` and a relabeling is requested. It will also display a warning message about this fact. After a reboot, once the SELinux state is `permissive` or `enforcing`, the role can be called again and then perform the SELinux relabeling.
> sap_general_preconfigure: Improve SELinux handling

- roles/sap_ha_pacemaker_cluster/README.md
- roles/sap_ha_pacemaker_cluster/defaults/main.yml
- roles/sap_ha_pacemaker_cluster/meta/argument_specs.yml
- roles/sap_ha_pacemaker_cluster/tasks/configure_nwas_ascs_ers_postinstallation.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_hana_common.yml
- roles/sap_ha_pacemaker_cluster/tasks/main.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/construct_vars_vip_resources_cloud_aws_ec2_vs.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/construct_vars_vip_resources_cloud_msazure_vm.yml
- roles/sap_ha_pacemaker_cluster/tasks/validate_input_parameters.yml
- using `WaitforStarted` to allow instances to finish starting up
- type change: `sap_ha_pacemaker_cluster_aws_vip_update_rt` must be a string, not a list
- improved and aligned search conditionals
> sap_ha_pacemaker_cluster: improved ASCS/ERS check logic

- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_vip_resources_default.yml
Fixes issue #512 - bad reference from previous VIP resource logic adjustments.
> sap_ha_pacemaker_cluster: fix: bad var reference - issue #512

- roles/sap_hana_preconfigure/README.md
- roles/sap_hana_preconfigure/defaults/main.yml
- roles/sap_hana_preconfigure/meta/argument_specs.yml
- roles/sap_hana_preconfigure/tasks/RedHat/assert-installation.yml
- roles/sap_hana_preconfigure/tasks/RedHat/installation.yml
Solves issue #500.
The new behavior if a system is running a RHEL version which is not in the list `sap_hana_preconfigure_supported_rhel_minor_releases` is as follows:
1. role running in **normal** mode:
a. `sap_hana_preconfigure_min_rhel_release_check: false` (default)
The debug task `Report if the system is running a RHEL release which is supported for SAP HANA` displays a warning message.
b. `sap_hana_preconfigure_min_rhel_release_check: true`
The assert task `Fail if the system is running a RHEL release which may not be supported for SAP HANA` fails with a failure message.
2. role running in **assert** mode, `sap_hana_preconfigure_assert: true`:
a. `sap_hana_preconfigure_min_rhel_release_check: false` (default)
The assert task `Report if the RHEL release is supported for SAP HANA` …
> sap_hana_preconfigure: Be less restrictive with new RHEL versions

- playbooks/vars/sample-variables-sap-swpm-advanced-mode-s4hana-onehost-install.yml
- playbooks/vars/sample-variables-sap-swpm-advanced-templates-mode.yml
- roles/sap_swpm/tasks/swpm/detect_variables.yml
- roles/sap_swpm/tasks/swpm/prepare_software.yml
- roles/sap_swpm/tasks/swpm/swpm_inifile_generate_advanced.yml
- roles/sap_swpm/tasks/swpm/swpm_inifile_generate_advanced_templates.yml
- roles/sap_swpm/tasks/swpm/swpm_inifile_generate_inifile_reuse.yml
- roles/sap_swpm/templates/configfile.j2
By default `#NW_getUnicode.isUnicode =` exists in inifile.params output, and defaults to true. In certain IBM Db2 executions, the automatic detection does not work and requires `NW_getUnicode.isUnicode = true` contained in the inifile.params. This value should already be true except for legacy NUC install files, which are no longer provided by SAP, therefore appending this into the default inifile block for IBM Db2 installations.
When executing advanced or inifile reuse, variable detection can fail. Added improved handling and consistent output (i.e. header of inifile.params).
For future, appended System Copy and Export variables to Jinja template as reference, and fixed DDIC password parameter which was in the incorrect section and could lead to SAP ECC Installation Export file failure …
> sap_swpm: variable corrections

- roles/sap_install_media_detect/files/tmp/sapfile
- roles/sap_install_media_detect/tasks/prepare/move_files_to_main_directory.yml
At the beginning, we currently need to move files from lower level directories to the top level so that all SAP archive files are in the same directory and the role always starts file handling at the same status (future versions might support using also the desired file location in separate subdirectories).
We want the role to only move files from directories the role is able to create, and leave all other directories in place, including their contents. This is the purpose of this PR.
Solves issue #523 .
> sap_install_media_detect: Leave non-role directories untouched

- roles/sap_install_media_detect/tasks/prepare/create_file_list_phase_1.yml
We add a task which asserts that a file with file name pattern `*SAPCAR*` has been found before. So the following task `SAP Install Media Detect - Prepare - Ensure sapcar is executable` will not failed because a variable has not been defined.
Solves #530.
> sap_install_media_detect: Handle missing SAPCAR

- roles/sap_install_media_detect/tasks/organize_files.yml
- roles/sap_install_media_detect/tasks/prepare/create_file_list_phase_2.yml
- roles/sap_install_media_detect/tasks/prepare/provide_sapfile_utility.yml
By defining variables for useful subsets of the sapfile results, we can use those variables for looping, thus limiting the output for several tasks significantly, especially in those cases where there are many SAP archive files in the software directory.
Solves issue #525.
> sap_install_media_detect: Don't loop too much

- roles/sap_swpm/tasks/pre_install/install_type.yml
Minor change to enable detection of HA installations using SAP SWPM 1.0
> sap_swpm: append other product id suffix

- meta/runtime.yml
- roles/sap_general_preconfigure/meta/runtime.yml
- roles/sap_ha_install_hana_hsr/meta/runtime.yml
- roles/sap_hana_install/meta/runtime.yml
- roles/sap_hana_preconfigure/meta/runtime.yml
- roles/sap_hostagent/meta/runtime.yml
- roles/sap_install_media_detect/meta/runtime.yml
- roles/sap_netweaver_preconfigure/meta/runtime.yml
- roles/sap_storage_setup/meta/runtime.yml
- roles/sap_swpm/meta/runtime.yml
Solves issue #507.
Note: We are using version 2.12 and not 2.14 to extend the range of possible control nodes to older releases (e.g. RHEL 8.6).
> collection: Enforce minimum ansible version 2.12

- roles/sap_ha_install_hana_hsr/tasks/configure_hsr.yml
- roles/sap_ha_install_hana_hsr/tasks/hdbuserstore.yml
- roles/sap_ha_install_hana_hsr/tasks/log_mode.yml
- roles/sap_ha_install_hana_hsr/tasks/pki_files.yml
- roles/sap_ha_pacemaker_cluster/tasks/configure_nwas_ascs_ers_postinstallation.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_common.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_stonith.yml
- roles/sap_ha_pacemaker_cluster/tasks/include_construct_vip_resources.yml
- roles/sap_ha_pacemaker_cluster/tasks/main.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/ascertain_platform_type.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/include_vars_platform.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/preconfigure_cloud_ibmcloud_vs.yml
Linter fixes, no functional changes.
> sap_ha_*: ansible-lint 6.22 fixes

- roles/sap_anydb_install_oracle/meta/runtime.yml
- roles/sap_ha_pacemaker_cluster/meta/runtime.yml
- roles/sap_hypervisor_node_preconfigure/meta/runtime.yml
- roles/sap_maintain_etc_hosts/meta/runtime.yml
- roles/sap_vm_preconfigure/meta/runtime.yml
This commit adds the file `meta/runtime.yml` to all those roles for which it was missing:
- `sap_anydb_install_oracle`
- `sap_ha_pacemaker_cluster`
- `sap_hypervisor_node_preconfigure`
- `sap_maintain_etc_hosts`
- `sap_vm_preconfigure`
Finally solves issue #507.
> collection: Enforce minimum ansible version 2.12, part 2

- roles/sap_hana_preconfigure/vars/RedHat_9.yml
I also updated most of the SAP note versions. There was no need for any change due to the updated content.
Solves issue #549.
> sap_hana_preconfigure: Implement RHEL 9.2 requirements

- .ansible-lint
- roles/sap_general_preconfigure/.ansible-lint
- roles/sap_general_preconfigure/handlers/main.yml
- roles/sap_general_preconfigure/tasks/RedHat/assert-installation.yml
- roles/sap_general_preconfigure/tasks/RedHat/generic/configure-selinux.yml
- roles/sap_general_preconfigure/tasks/RedHat/generic/configure-tmpfs.yml
- roles/sap_general_preconfigure/tasks/RedHat/installation.yml
- roles/sap_general_preconfigure/tasks/SLES/assert-installation.yml
- roles/sap_general_preconfigure/tasks/SLES/installation.yml
> sap_general_preconfigure: cleanup for ansible-lint 6.22.0

- roles/sap_general_preconfigure/tasks/RedHat/generic/configure-hostname.yml
- roles/sap_hana_install/tasks/hana_addhosts.yml
- roles/sap_hana_install/tasks/hana_exists.yml
- roles/sap_hana_preconfigure/tasks/RedHat/installation.yml
This commit makes the roles compatible with the following versions of `ansible-core`:
- 2.16.1
- 2.15.8
- 2.14.12 when running in normal (=non-assert) mode.
The preconfigure roles also support an extended check mode, called assert mode, in which the roles do not change anything but verify if all settings are correct. This commit will not cover the assert mode. So several tasks of the preconfigure roles in assert mode will fail. By using the `_assert_ignore_errors` role parameters in assert mode, the roles will not fail but the affected tasks will not be executed so those settings will not be validated.
Relates to issues #555 and #556.
> various roles: Fix issue sap-linuxlab#556 for non-assert runs

- roles/sap_hana_preconfigure/tasks/RedHat/assert-installation.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-tuned.yml
- roles/sap_netweaver_preconfigure/tasks/sapnote/2526952.yml
- roles/sap_netweaver_preconfigure/tasks/sapnote/assert-2526952.yml
> preconfigure roles: Avoid role aborts during assert runs

- roles/sap_general_preconfigure/defaults/main.yml
... for the three variables sap_hostname, sap_domain, sap_ip.
Those are used in many places in the role and the effort for changing and testing the code is too high given that we plan to replace this part of the role by the new role sap_maintain_etc_hosts.
Relates to #589.
> sap_general_preconfigure: skip var-naming[no-role-prefix]

- roles/sap_vm_preconfigure/.ansible-lint
- roles/sap_vm_preconfigure/handlers/platform/redhat_rhel_kvm_vm/main.yml
- roles/sap_vm_preconfigure/tasks/detect_platform/main.yml
- roles/sap_vm_preconfigure/tasks/platform/hyp_redhat_rhel_kvm_vm/assert-set-tuned-profile.yml
- roles/sap_vm_preconfigure/tasks/platform/hyp_redhat_rhel_kvm_vm/main.yml
- roles/sap_vm_preconfigure/tasks/platform/hyp_redhat_rhel_kvm_vm/set-tuned-profile.yml
Implemented the ansible-lint suggestions.
There are three open issues in code you have added @sean-freeman, could you please take a look?
```
yaml[indentation]: Wrong indentation: expected 4 but found 2
tasks/detect_platform/main.yml:82
yaml[indentation]: Wrong indentation: expected 4 but found 2
tasks/detect_platform/main.yml:115
yaml[empty-lines]: Too many blank lines (1 > 0)
tasks/detect_platform/main.yml:131
```
> sap_vm_preconfigure: implement ansible-lint changes

- .github/workflows/ansible-lint-sap_general_preconfigure.yml
- .github/workflows/ansible-lint-sap_ha_install_hana_hsr.yml
- .github/workflows/ansible-lint-sap_ha_pacemaker_cluster.yml
- .github/workflows/ansible-lint-sap_hana_install.yml
- .github/workflows/ansible-lint-sap_hana_preconfigure.yml
- .github/workflows/ansible-lint-sap_hypervisor_node_preconfigure.yml
- .github/workflows/ansible-lint-sap_install_media_detect.yml
- .github/workflows/ansible-lint-sap_maintain_etc_hosts.yml
- .github/workflows/ansible-lint-sap_netweaver_preconfigure.yml
- .github/workflows/ansible-lint-sap_reusable_workflow.yml
- .github/workflows/ansible-lint-sap_storage_setup.yml
- .github/workflows/ansible-lint-sap_swpm.yml
- .github/workflows/ansible-lint-sap_vm_preconfigure.yml
- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-test-sanity.yml
for reference: https://github.com/sap-linuxlab/community.sap_install/discussions/421
Closes #420
> fix(.github/workflows): update all the workflows

- playbooks/sample-sap-hypervisor-redhat_ocp_virt-preconfigure.yml
- playbooks/vars/sample-variables-sap-hypervisor-node-preconfigure-rh_ocp_virt.yml
- roles/sap_hypervisor_node_preconfigure/tasks/main.yml
- roles/sap_hypervisor_node_preconfigure/tasks/platform/redhat_ocp_virt/install-cnv-operator.yml
- roles/sap_hypervisor_node_preconfigure/tasks/platform/redhat_ocp_virt/main.yml
- roles/sap_hypervisor_node_preconfigure/tasks/platform/redhat_ocp_virt/setup-worker-nodes.yml
When testing the ansibe-galaxy community version, a couple of issues occurred that are fixed with this PR.
1. Role name is community.sap_install.sap_hypervisor_node_preconfigure (adjusted in example playbook)
2. When doing include_tasks, the path has to be relative to the role top tasks directory.
3. Reads the KUBECONFIG environment variable and sets the environment for the playbook accordingly.
> sap_hypervisor_node_preconfigure: Fixed role name and path for include tasks

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
Main changes from previous version 1.3.4:
- sap_hypervisor_node_preconfigure: Bug fix for role name and path for included tasks
> collection: prepare for v1.3.5

- roles/sap_hana_preconfigure/tasks/SLES/configuration.yml
- roles/sap_netweaver_preconfigure/tasks/SLES/configuration.yml
> sap_*_preconfigure: disable and stop sapconf when saptune run

- roles/sap_general_preconfigure/defaults/main.yml
- roles/sap_general_preconfigure/meta/argument_specs.yml
- roles/sap_general_preconfigure/tasks/RedHat/configuration.yml
- roles/sap_general_preconfigure/tasks/RedHat/generic/assert-dns-name-resolution.yml
- roles/sap_general_preconfigure/tasks/RedHat/generic/assert-etc-hosts.yml
- roles/sap_general_preconfigure/tasks/RedHat/generic/assert-hostname.yml
- roles/sap_general_preconfigure/tasks/RedHat/generic/check-dns-name-resolution.yml
- roles/sap_general_preconfigure/tasks/RedHat/generic/configure-etc-hosts.yml
- roles/sap_general_preconfigure/tasks/RedHat/generic/configure-hostname.yml
- roles/sap_general_preconfigure/tasks/sapnote/2002167/03-setting-the-hostname.yml
- roles/sap_general_preconfigure/tasks/sapnote/2772999/03-configure-hostname.yml
- roles/sap_general_preconfigure/tasks/sapnote/3108316/03-configure-hostname.yml
We want to use a central role for all `/etc/hosts` related manipulation (it is part of this collection already), so let's start with `sap_general_preconfigure`.
At the same time, we can use new role variables which include the role prefix, replacing the previous "global" variables `sap_ip`, `sap_hostname`, and `sap_domain` in `defaults/main.yml` (while still being compatible).
I expect merge conflicts with https://github.com/sap-linuxlab/community.sap_install/pull/653 but it should not be too difficult to solve them, just annoying.
> sap_general_preconfigure: Use the role sap_maintain_etc_hosts - RHEL systems

- roles/sap_maintain_etc_hosts/defaults/main.yml
- roles/sap_maintain_etc_hosts/meta/argument_specs.yml
- roles/sap_maintain_etc_hosts/tasks/update_host_absent.yml
- roles/sap_maintain_etc_hosts/tasks/update_host_present.yml
Checking the ip address against a regex pattern should be sufficient to ensure that valid IP addresses are passed to the role.
Solves issue #667.
Should not cause merge conflicts with #668 but probably worth checking.
> sap_maintain_etc_hosts: no longer use ansible.utils.ip

- roles/sap_maintain_etc_hosts/tasks/update_host_absent.yml
- roles/sap_maintain_etc_hosts/tasks/update_host_present.yml
Also fixes some typos.
Solves issue #662.
> sap_maintain_etc_hosts: Fix wrong assert messages

- .github/workflows/check_outdated_dependencies.yml
- requirements-workflow.txt
- workflows/check_outdate_deps/Dockerfile
- workflows/check_outdate_deps/action.yml
- workflows/check_outdate_deps/check_outdate_deps.sh
- workflows/check_outdate_deps/open_issue.py
Refs https://github.com/sap-linuxlab/community.sap_install/discussions/421#discussioncomment-8457445
> feat(workflows): create a workflow to open issue when outdate deps

- roles/sap_hana_preconfigure/tasks/SLES/configuration.yml
> sap_hana_preconfigure: update kernel parameters for SLES

- roles/sap_general_preconfigure/tests/run-sap_general_preconfigure-tests.py
- roles/sap_hana_install/tests/install/run-sap_hana_install-install-tests.py
- roles/sap_hana_preconfigure/tests/run-sap_hana_preconfigure-tests.py
- roles/sap_netweaver_preconfigure/tests/run-sap_netweaver_preconfigure-tests.py
Fixes #671.
And solves the wrong integration branch chosen in https://github.com/sap-linuxlab/community.sap_install/pull/672 .
> collection: Use -i instead of -l test scripts

- roles/sap_swpm/defaults/main.yml
- roles/sap_swpm/tasks/swpm.yml
- roles/sap_swpm/tasks/swpm/prepare_software.yml
This PR supports optionally skipping setting permission and ownership of SAP installation files. It also introduces new role parameters for setting the mode, owner, and group of the software directory, the directory for SAPCAR, and the directory for SWPM, as well as the files within.
Solves issue #663.
> sap_swpm: optionally skip setting file permissions

- roles/sap_swpm/tasks/swpm.yml
This is to address issue #681, which was created because an error was thrown complaining about the name in the label.
I noticed that the new name had been added 2 tasks above, and then I used the same label name on the last task and re-executed the playbook, which then finished successfully.
> sap_swpm: Fix item label in swpm.yml

- roles/sap_ha_pacemaker_cluster/defaults/main.yml
- roles/sap_ha_pacemaker_cluster/tasks/configure_srhook.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_hana_common.yml
- roles/sap_ha_pacemaker_cluster/tasks/import_hacluster_vars_from_inventory.yml
- roles/sap_ha_pacemaker_cluster/vars/hana_scaleout_common.yml
- roles/sap_ha_pacemaker_cluster/vars/hana_scaleup_common.yml
- roles/sap_ha_pacemaker_cluster/vars/nwas_common.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_aws_ec2_vs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_gcp_ce_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_ibmcloud_powervs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_ibmcloud_vs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_msazure_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_hyp_ibmpower_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/redhat.yml
- roles/sap_ha_pacemaker_cluster/vars/suse.yml
This PR changes:
1. Platform vars are now using variable dictionaries sourced from os_family vars for easier control from each of them.
2. New variables implemented to cover os_family differences:
- aws fence agent
- SRhook path
- ocf SAP agents namespace
3. nwas_common.yml was adjusted to be more dynamic and source from dictionary
I have tested this code on SLES for SAP SP5 and RHEL9.2 along with changes in ha_cluster.
@sean-freeman Thank you for call yesterday to double check contents with me.
> sap_ha_pacemaker_cluster: Variable changes for different os and platforms

- roles/sap_netweaver_preconfigure/tasks/sapnote/3119751.yml
- roles/sap_netweaver_preconfigure/tasks/sapnote/assert-3119751.yml
- roles/sap_netweaver_preconfigure/vars/RedHat_8.yml
We need to sync the role `sap_netweaver_preconfigure` with the latest status of SAP note 3119751:
For RHEL 8, the following needs to be done to be prepared for all SAP kernels which are supported on RHEL 8 so that the SAP kernel can find the GCC10 symbols:
- In directory `/opt/rh/SAP/lib64` (the directory where the shared libraries of the `compat-sap-c++-<version>` package(s) are placed), a symlink named `libstdc++.so.6` needs to be present, pointing to file `compat-sap-c++-<version>.so` in the same directory, with `<version>` being `10` or higher.
- For certain older versions of the SAP kernel, there needs to be an additional symlink in directory `/usr/sap/lib`, named  `libstdc++.so.6` and pointing to file `/opt/rh/SAP/lib64/libstdc++.so.6`. This is because `RPATH` for older kernels did …
> sap_netweaver_preconfigure-RHEL: Sync with SAP note 3119751 v.13

- roles/sap_install_media_detect/files/tmp/sapfile
Relates to issue #699.
We don't introduce a new file type because the file named `51057035` (renamed by the role to `51057035.zip` before `sapfile` is called) will be detected as type `sap_export_nwas_java`, which should be sufficient for correct processing.
> sap_install_media_detect: Improve SAP file type detection in sapfile

- roles/sap_hana_install/README.md
Updated README as per suggestions in PR: sap_hana_install: update README.md #722.
Clearification on the description of section "Perform Initial Checks". Those checks will only be skipped if "sap_hana_install_force" is set to "true".
> sap_hana_install: Update README.md regarding parameter sap_hana_install_force

- roles/sap_general_preconfigure/tasks/RedHat/generic/assert-etc-hosts.yml
> sap_general_preconfigure: Fix /etc/hosts check in assert mode

- roles/sap_install_media_detect/tasks/prepare/create_file_list_phase_2.yml
> sap_install_media_detect: Detection of duplicate SAR files for EXE, EXEDB, igs, igshelper and webdisp should count only file with type=sapcar

- roles/sap_ha_pacemaker_cluster/README.md
- roles/sap_ha_pacemaker_cluster/defaults/main.yml
- roles/sap_ha_pacemaker_cluster/meta/argument_specs.yml
- roles/sap_ha_pacemaker_cluster/tasks/Suse/post_steps_nwas_abap_ascs_ers.yml
- roles/sap_ha_pacemaker_cluster/tasks/configure_nwas_ascs_ers_postinstallation.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_hana_scaleup.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_hana_scaleup_angi.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_nwas_abap_ascs_ers.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_nwas_abap_ascs_ers_simple_mount.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_vip_constraints_hana.yml
- roles/sap_ha_pacemaker_cluster/tasks/main.yml
- roles/sap_ha_pacemaker_cluster/vars/redhat.yml
- roles/sap_ha_pacemaker_cluster/vars/suse.yml
@ja9fuchs Lets review it together next week when you are available.
This PR adds new feature: Simple Mount scenario for ASCS ERS cluster.
Changes:
1. Simple Mount added as separate task, enabled by as default ASCS cluster for SUSE, disabled for Red Hat and marked as TODO when SAPStartSrv agent is available.  Controlled by variable `sap_ha_pacemaker_cluster_nwas_abap_ascs_ers_simple_mount`
2. Added more variables for cluster resources and updated naming to align with previous changes: variables for order, colocation and groups.
3. Added IS_ERS parameter, which is valid for all 3 scenarios.
4. New entry for SAPStartSrv in resource agent dictionary `__sap_ha_pacemaker_cluster_resource_agents`
Requirement: Simple mount uses shared NFS for both ASCS and ERS data across both nodes, …
> sap_ha_pacemaker_cluster: ASCS ERS Simple Mount

- roles/sap_ha_pacemaker_cluster/tasks/Suse/post_steps_nwas_abap_ascs_ers.yml
- roles/sap_ha_pacemaker_cluster/tasks/configure_nwas_ascs_ers_postinstallation.yml
Scope:
1. Moved python3-pip code from sap_swpm to sap_ha_pacemaker_cluster to enable change in https://github.com/sap-linuxlab/community.sap_install/pull/720 for @berndfinger 
2. Added throttling and retry loop for tasks touching files on cross-mounted NFS filesystem under ASCS ERS, which was not working correctly on MS Azure NFS filesystems. It will now do change on first host by using `throttle: 1` then it will retry-loop attempt to do change on second node. @ja9fuchs 
> Testing has shown that it takes 20-40 seconds for NFS to be accessible again.
> sap_ha_pacemaker_cluster: Add python3-pip and NFS fix for Azure

- roles/sap_hana_install/defaults/main.yml
- roles/sap_hana_install/meta/argument_specs.yml
- roles/sap_hana_install/tasks/assert-addhosts-loop-block.yml
- roles/sap_hana_install/tasks/hana_addhosts.yml
- roles/sap_hana_install/tasks/hana_exists.yml
- roles/sap_hana_install/tasks/post_install.yml
- roles/sap_hana_install/tasks/pre_install.yml
- roles/sap_hana_install/templates/fapolicyd-rules.j2
- roles/sap_hana_install/tests/install/hana-uninstall.yml
- roles/sap_hana_install/tests/install/install-vars.yml
This PR adds support for fapolicyd:
- The presence of the package `fapolicyd` is ensured.
- The integrity setting in `/etc/fapolicyd/fapolicyd.conf` will be `sha256` instead of the default `none`.
- The presence of a new fapolicyd rule file in `/etc/faplicyd/rules.d`, for protecting shell scripts, is ensured. 
- The presence of all executables under `/hana` and `/usr/sap` in fapolicyd trust files in `/etc/faplicyd/trust.d` is ensured.
- The service `fapolicyd` is enabled and running.
I introduced a new role parameter, `sap_hana_install_root_path` which is needed for this functionality, and replaced `/hana` by this variable and `/hana/shared` by its corresponding variable.
I also modified `yes/no` to `true/false` in `defaults/main.yml` so we over time only use those for all roles.
Solves …
> sap_hana_install: Add support for fapolicyd

- roles/sap_hana_install/tasks/post_install.yml
- roles/sap_hana_install/tasks/pre_install.yml
Two of the tasks were enabled even when `sap_hana_install_use_fapolicyd` was set to `false`. This PR fixes the issue and ensures that all the fapolicyd tasks are now inside blocks which are only active when `sap_hana_install_use_fapolicyd` is `true`.
> sap_hana_install: Fix issue 756

- roles/sap_general_preconfigure/tasks/RedHat/installation.yml
... for installing packages, except for RHEL 8.1.
Solves issue #755.
> sap_general_preconfigure: Use the package module in most cases

- roles/sap_ha_pacemaker_cluster/tasks/configure_nwas_ascs_ers_postinstallation.yml
`pcs resource restart` on RHEL only takes one resource argument and reads the 2nd one as a target node argument.
The task was converted to simply run the restart per resource in a loop.
> sap_ha_pacemaker_cluster: fix pcs resource restart

- roles/sap_install_media_detect/tasks/cleanup/disable-epel-repo.yml
- roles/sap_install_media_detect/tasks/prepare/enable_rar_handling.yml
sap_install_media_detect: aws igw slow impact gpg key
Consistent failures in 3 tasks where the AWS IGW performance is too slow and timeout occurs, causing Ansible to have a fatal error. Fixed with retries while waiting for the SNAT to work.
> sap_install_media_detect: aws igw slow impact gpg key

- roles/sap_swpm/tasks/pre_install/create_os_user.yml
- roles/sap_swpm/tasks/pre_install/install_type/ha_install.yml
- roles/sap_swpm/tasks/pre_install/install_type/ha_maint_plan_stack_install.yml
Legacy code for ASCS HA, traced to original IBM LSS code which does not contain any reasoning for this code to exist
The code appears to serve no function but does cause ASCS HA <sid>adm to not default to C Shell, which is problematic for runtime stability
Tested an execution of ASCS HA without this code, and it installed ASCS HA successfully (with correct use of C Shell default for <sid>adm)
Therefore, commented out the call that imports Ansible Tasks from file `create_os_user.yml` and in future suggest this code is removed entirely
> sap_swpm: legacy ascs ha code

- roles/sap_install_media_detect/tasks/prepare/move_files_to_main_directory.yml
sap_install_media_detect: search known subdirs on re-run
> sap_install_media_detect: search known subdirs on re-run

- roles/sap_swpm/defaults/main.yml
- roles/sap_swpm/tasks/pre_install.yml
> sap_swpm: Option to enable SWPM observer mode

- roles/sap_general_preconfigure/tasks/RedHat/generic/check-dns-name-resolution.yml
Also included a minor task description change to make it clearer what has failed.
> sap_general_preconfigure: Don't ignore DNS A/PTR record inconsistencies, this should fail the check is negative

- roles/sap_general_preconfigure/defaults/main.yml
- roles/sap_general_preconfigure/tasks/RedHat/generic/check-dns-name-resolution.yml
> sap_general_preconfigure: Revert to ignoring DNS failures

- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_common.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_aws_ec2_vs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_gcp_ce_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_msazure_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/redhat.yml
- roles/sap_ha_pacemaker_cluster/vars/suse.yml
Changes:
- Add `__sap_ha_pacemaker_cluster_corosync_totem_default` in OS variable files with baseline corosync totem settings
- Add `__sap_ha_pacemaker_cluster_corosync_totem_platform` in Platform variable files with recommended corosync totem settings
- Rework logic inside of construct_vars_common.yml to become dynamic - Platform totem is combined with OS totem, where Platform can overwrite OS values as required.
```yaml
```
Tested on:
- SLES15 SP5 - SAP ASCS/ERS and HANA clusters
**Note 1:** 
This change is now applicable to SUSE after changes in ha_cluster https://github.com/linux-system-roles/ha_cluster/pull/212
**Note 2:**
Platform specific totem values are taken from comprehensive configuration in crmsh https://github.com/ClusterLabs/crmsh/blob/master/etc/profiles.yml
> sap_ha_pacemaker_cluster: Enhance corosync totem handling

- roles/sap_swpm/tasks/swpm.yml
This PR is a essentially a reopening of https://github.com/sap-linuxlab/community.sap_install/pull/720 after version 1.4.1 has been published.
Solves issue #719.
Advantages:
- No dependency on community.general in the role sap_swpm, simplifying support for downstream versions
- No more Python related package installations at the beginning of the role
> sap_swpm: Remove the pids module

- docs/developer_notes/sap_swmp_dev.md
sap_swpm: add error notes to dev doc, include prettified versions of the (very long) error messages/strings
For obvious reason, these are some common error messages and do not encompass all error messages and the resulting fix.
> sap_swpm: add error notes to dev doc

- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-tsx.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/enable-tsx.yml
> sap_hana_preconfigure: Enable TSX also for RHEL 9

- roles/sap_general_preconfigure/handlers/main.yml
- roles/sap_hana_preconfigure/handlers/main.yml
This PR adds Suse specific check for zypper to ensure that it is not locked by time both roles are finished.
Applies to:
```
sap_general_preconfigure
sap_hana_preconfigure
```
Execution example:
```console
RUNNING HANDLER [/mnt/c/scripts/community.sap_install/roles/sap_hana_preconfigure : Reboot the managed node] ************************************************
changed: [s01s4hana]
RUNNING HANDLER [/mnt/c/scripts/community.sap_install/roles/sap_hana_preconfigure : Wait for Zypper lock to be released] ************************************
FAILED - RETRYING: [s01s4hana]: Wait for Zypper lock to be released (60 retries left).
ok: [s01s4hana]
```
Solves: https://github.com/sap-linuxlab/community.sap_install/issues/791
> sap_hana_preconfigure/SLES: Zypper lock handler for #791

- roles/sap_storage_setup/tasks/generic_tasks/configure_nfs_filesystems.yml
Description:
1. Changes IF blocks to ELIF for simplification.
2. Add /hana/* block required for SAP HANA Scaleout
```yaml
{%- elif nfs_item.mountpoint.startswith('/hana/') %}
{%- set add_hana = mount_list.extend([
{
'mount_src': nfs_item.nfs_path | regex_replace('/$', ''),
'mountpoint': nfs_item.mountpoint | regex_replace('/$', ''),
}
]) %}
```
> sap_storage_setup: Add support for HANA Scaleout NFS filesystems

- roles/sap_swpm/tasks/post_install.yml
> sap_swpm: hdbuserstore default connection should use sap_swpm_db_schema_abap_password

- roles/sap_hana_install/defaults/main.yml
- roles/sap_hana_install/tasks/hana_install.yml
Solves issue #804.
@marcelmamula - Thanks for reporting, proposing a possible solution, and initial testing!
> sap_hana_install: Use polling for hdblcm

- roles/sap_ha_pacemaker_cluster/README.md
- roles/sap_ha_pacemaker_cluster/defaults/main.yml
- roles/sap_ha_pacemaker_cluster/meta/argument_specs.yml
- roles/sap_ha_pacemaker_cluster/tasks/Suse/pre_steps_hana.yml
Description:
- Adds variable `sap_ha_pacemaker_cluster_saphanasr_angi_detection` that enables option to disable SAPHanaSR-angi detection to install Classic agents even on servers where Angi is available.
> sap_ha_pacemaker_cluster: Add override to use Classic SAPHanaSR agents

- roles/sap_ha_install_anydb_ibmdb2/tasks/db2_hadr_enable.yml
- roles/sap_ha_install_anydb_ibmdb2/tasks/db2_hadr_pcmk_cluster_create.yml
- roles/sap_ha_install_anydb_ibmdb2/tasks/main.yml
- roles/sap_ha_install_anydb_ibmdb2/tasks/passwordless_ssh.yml
- roles/sap_ha_install_anydb_ibmdb2/tasks/platform/ascertain_platform_type.yml
- roles/sap_ha_install_anydb_ibmdb2/tasks/platform/db2cm_cloud_aws_ec2_vs.yml
- roles/sap_ha_install_anydb_ibmdb2/tasks/platform/db2cm_cloud_gcp_ce_vm.yml
- roles/sap_ha_install_anydb_ibmdb2/tasks/platform/db2cm_cloud_msazure_vm.yml
Added linting fixes and appended additional logic to provide further idempotency
At request and in parallel, tested with SLES 15 SP5 + `IBM Db2 for LUW 11.5 MP8 FP0 SAP2 LINUX x86_64` and provided bug fixes accordingly. Db2 version was chosen to assess compatibility of older release with latest patched OS
> sap_ha_install_anydb_ibmdb2: linting and sles bug fixes

- requirements.yml
for fixing the galaxy-importer error "syntax-check[unknown-module]: couldn'\''t resolve module/action '\''community.general.zypper'\''"
> collection: Add collection dependency for community.general

- roles/sap_hana_preconfigure/tasks/SLES/configuration.yml
- roles/sap_hana_preconfigure/tasks/SLES/installation.yml
- roles/sap_netweaver_preconfigure/tasks/SLES/configuration.yml
For SLES, `sapconf` should be stopped but will error if the package does not exist and further errors for `hdblcm` if the base OS Image does not include `insserv-compat`.
> sap_*preconfigure: edge case handling for sles pkgs

- roles/sap_general_preconfigure/handlers/main.yml
- roles/sap_general_preconfigure/tasks/RedHat/generic/configure-kernel-parameters.yml
- roles/sap_general_preconfigure/tasks/RedHat/installation.yml
- roles/sap_hana_preconfigure/tasks/RedHat/installation.yml
- roles/sap_hana_preconfigure/tasks/sapnote/2055470.yml
- roles/sap_hana_preconfigure/tasks/sapnote/2382421.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3024346.yml
These changes should ensure that the molecule idempotency tests no longer fail, see issue #752.
> Fixes for testing with molecule

- .yamllint.yml
- roles/sap_general_preconfigure/tasks/RedHat/generic/increase-nofile-limits.yml
- roles/sap_general_preconfigure/tasks/RedHat/generic/increase-nproc-limits.yml
- roles/sap_hana_install/tasks/pre_install/extract_sarfile.yml
- roles/sap_hana_install/tasks/pre_install/prepare_sarfiles.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/configure-cpu-governor-for-performance.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/configure-epb.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/disable-coredumps.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/disable-ksm.yml
- roles/sap_hana_preconfigure/tasks/sapnote/2055470.yml
- roles/sap_hana_preconfigure/tasks/sapnote/2382421.yml
- roles/sap_hana_preconfigure/tasks/sapnote/2684254/configuration.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3024346.yml
- roles/sap_storage_setup/tasks/generic_tasks/configure_swap.yml
ansible-lint 24.7.0 produced:
```
WARNING  Found incompatible custom yamllint configuration (.yamllint.yml), please either remove the file or edit it to comply with:
- comments.min-spaces-from-content must be 1
- octal-values.forbid-implicit-octal must be true
- octal-values.forbid-explicit-octal must be true.
```
This PR ensures that the collection is yamllint clean again.
Relates to issue #810.
> collection: Modify for latest yamllint requirements

- roles/sap_hana_preconfigure/README.md
- roles/sap_hana_preconfigure/defaults/main.yml
- roles/sap_hana_preconfigure/meta/argument_specs.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3024346.yml
- roles/sap_hana_preconfigure/tasks/sapnote/assert-3024346.yml
- roles/sap_hana_preconfigure/vars/RedHat_7.yml
- roles/sap_hana_preconfigure/vars/RedHat_8.yml
- roles/sap_hana_preconfigure/vars/RedHat_9.yml
Necessary changes for getting in sync with the latest version of SAP note 3024346
> sap_hana_preconfigure/RHEL/NetApp: Sync with SAP note 3024346 v.10

- roles/sap_hana_preconfigure/README.md
- roles/sap_hana_preconfigure/tasks/SLES/assert-configuration.yml
- roles/sap_hana_preconfigure/tasks/SLES/configuration.yml
> fix(sap_hana_preconfigure): Update azure override readme

- roles/sap_install_media_detect/tasks/prepare/move_files_to_main_directory.yml
sap_install_media_detect: fix syntax (#773)
> sap_install_media_detect: fix syntax

- roles/sap_general_preconfigure/tasks/sapnote/2002167/03-setting-the-hostname.yml
- roles/sap_general_preconfigure/tasks/sapnote/2772999/03-configure-hostname.yml
- roles/sap_general_preconfigure/tasks/sapnote/3108316/03-configure-hostname.yml
We need to use the FQCN when importing the role sap_maintain_etc_hosts.
Solves issue #826.
> sap_general_preconfigure: Use FQCN for import_role

- roles/sap_ha_pacemaker_cluster/README.md
- roles/sap_ha_pacemaker_cluster/defaults/main.yml
- roles/sap_ha_pacemaker_cluster/meta/argument_specs.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_final_hacluster_vars.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_common.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_stonith.yml
- roles/sap_ha_pacemaker_cluster/tasks/import_hacluster_vars_from_inventory.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/preconfigure_cloud_aws_ec2_vs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_aws_ec2_vs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_gcp_ce_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_ibmcloud_powervs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_ibmcloud_vs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_msazure_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_hyp_ibmpower_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/redhat.yml
- roles/sap_ha_pacemaker_cluster/vars/suse.yml
**New features:**
- **Stonith SBD fence method added with all extra variables required for `ha_cluster`**
- Significant changes to Stonith task file, adding lot of extra validations to avoid execution if:
- `ha_cluster` variables are provided, just skip them because you cannot override precedence anyway
- variables are empty, not required list or string where list is expected (iterable check fails to differentiate between string and list)
- New repository dictionaries:
- `__sap_ha_pacemaker_cluster_repos_dict` defined inside OS vars
- Each platform vars loads `__sap_ha_pacemaker_cluster_repos` from dictionary
- Dictionary is empty for SUSE as it comes with subscription.
- New fence agent dictionaries for each platform
- `__sap_ha_pacemaker_cluster_stonith_default_dict` defined in each …
> sap_ha_pacemaker_cluster: Stonith SBD enablement, stonith and repos dictionaries

- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_aws_ec2_vs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_gcp_ce_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_ibmcloud_powervs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_ibmcloud_vs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_msazure_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_hyp_ibmpower_vm.yml
**Description:**
- Enhanced corosync totem variables for each platform based on Cloud providers
- Switch to dictionary, similar to stonith dictionary
- Added documentation links
**Important:**
- Some dictionaries are simplified because there are no differences either between OS or HANA/NWAS - Similar to stonith dictionaries.
**Example for AWS, which includes differences for both OS and host type:**
```yaml
__sap_ha_pacemaker_cluster_corosync_totem_platform_dict:
redhat_hana:
options:
token: 30000
redhat_nwas:
options:
token: 30000
suse_hana:
options:
token: 30000
consensus: 36000
token_retransmits_before_loss_const: 6
clear_node_high_bit: 'yes'
suse_nwas:
options:
token: 30000
consensus: 36000
clear_node_high_bit: 'yes'
__sap_ha_pacemaker_cluster_corosync_totem_platform:
"{{ …
```
> sap_ha_pacemaker_cluster: Corosync Totem platform dictionary

- roles/sap_ha_pacemaker_cluster/vars/suse.yml
Description:
- Added package `fence-agents-azure-arm` to dictionary `__sap_ha_pacemaker_cluster_fence_agent_packages_dict` in SUSE variable files.
Reason:
- Azure fence agent was separated from main package as part of https://www.suse.com/support/kb/doc/?id=000021504
```yaml
__sap_ha_pacemaker_cluster_fence_agent_packages_dict:
cloud_msazure_vm:
- fence-agents-azure-arm
```
> sap_ha_pacemaker_cluster/SLES: New azure fence agent package

- docs/README.md
- requirements-workflow.txt
ansible 9.5.1 (core 2.16.9) require minimal version of python 3.10.14
Closes #710 (not update to latest, but worth clean history of issue)
Closes #711
Closes #712 (not update to latest, but worth clean history of issue)
Closes #713
***Once this PR is merged, the above issues will also be closed, after that, the first week of next month the automation will create new ones with clean logs***
> feat(requirements): update requirements with ansible 9.5.1

- roles/sap_storage_setup/tasks/generic_tasks/map_single_disks_to_filesystems.yml
- Current disk assignment works on approximate validation with `(disk_size_gb-8) <= fs.disk_size <= (disk_size_gb+8)` which invalidates this role when filesystems with less than 8 GB differences are used.
- Current loop will pick first found, invalidating correct entries, causing cascading failure during LV creation because of `device: ""`
Disks with sizes 15, 20 and 25 are used.
**/hana/shared will never be loaded, because `/hana/log` will find 25GB disk, use it and `/hana/shared` would be left without entry in following list of disks.`volume_map`**
```yaml
sap_storage_setup_definition: [
{
"disk_size": 15,
"filesystem_type": "xfs",
"mountpoint": "/hana/data",
"name": "hana_data"
},
{
"disk_size": 20,
"filesystem_type": "xfs",
"mountpoint": "/hana/log",
"name": "hana_log"
},
{ …
```
> sap_storage_setup: Add exact size disk check on top of approximate check

- roles/sap_swpm/tasks/pre_install.yml
> sap_swpm:  fix issue #792 - error when observer user defined, but empty and observer mode is on

- roles/sap_hana_install/tasks/main.yml
Fixes #844.
With this change, the role sap_hana_install can be used to perform an SAP HANA installation check without performing an installation.
> sap_hana_install: Implement an SAP HANA installation check only feature

- roles/sap_ha_pacemaker_cluster/tasks/platform/preconfigure_cloud_gcp_ce_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_aws_ec2_vs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_gcp_ce_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_ibmcloud_powervs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_ibmcloud_vs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_msazure_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_hyp_ibmpower_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/redhat.yml
- roles/sap_ha_pacemaker_cluster/vars/suse.yml
1. GCP Preconfigure task was moved to block to execute only if proper `gcp_nlb_reserved_ip_haproxy` method is used. This is not necessary for `ipaddr` method.
2. New `__sap_ha_pacemaker_cluster_sap_extra_packages_dict` dictionary in OS var files to accommodate override over default VIP method. This is similar dictionary implementation as done before for stonith, extra packages and others.
haproxy is not documented method to be used on SUSE as per documentation from Google.
```yaml
```
> sap_ha_pacemaker_cluster: GCP haproxy handling and new platform VIP dictionary

- roles/sap_hana_preconfigure/vars/RedHat_8.yml
Solves issue #867.
Successfully tested against `x86_64` and `ppc64le` managed nodes.
> sap_hana_preconfigure: Add RHEL 8.10

- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_nwas_abap_ascs_ers.yml
Fixing the order of the resources in ASCS and ERS resource groups.
The VIP resource has to be the first to be started and the last to be stopped.
This will align the automation with the documentation by all providers.
RHEL 9.4 on AWS
> fix: vip resources must be first in ASCS/ERS resource groups

- roles/sap_hana_preconfigure/vars/RedHat_9.yml
> sap_hana_preconfigure: No longer set net.core.somaxconn in RHEL 9

- roles/sap_netweaver_preconfigure/defaults/main.yml
- roles/sap_netweaver_preconfigure/tasks/RedHat/installation.yml
- roles/sap_netweaver_preconfigure/vars/RedHat_7.yml
- roles/sap_netweaver_preconfigure/vars/RedHat_8.yml
- roles/sap_netweaver_preconfigure/vars/RedHat_9.yml
Solves issue #689.
Further changes in this commit:
- Add the SAP note numbers and versions in a comment before the list of packages in the RedHat*.yml files in vars.
- Add 'ansible_architecture' as a condition in the related installation task, so that there is no task failure when running on another architecture than 'x86_64'.
- Also revert back to the default of 'false' for the role variable 'sap_netweaver_preconfigure_use_adobe_doc_services'. See commit 384f4d82, PR #876.
> sap_netweaver_preconfigure: Sync with applicable SAP notes for Adobe DS

- roles/sap_hana_preconfigure/vars/RedHat_9.yml
SAP HANA 2.0 SPS08 is built with GCC13, so we need to install compat-sap-c++-13.
Solves #893.
> sap_hana_preconfigure: Add compat-sap-c++-13

- roles/sap_swpm/tasks/pre_install/detect_variables_from_inifile.yml
- roles/sap_swpm/tasks/pre_install/generate_inifile.yml
- roles/sap_swpm/tasks/pre_install/swpm_prepare.yml
> sap_swpm: Fix issues with localhost delegation on certain control nodes

- roles/sap_hana_install/README.md
- roles/sap_hana_install/defaults/main.yml
This is required when installing the HANA component 'LSS', which is the default in HANA 2.0 SPS08. The installation execution mode can be set to the previous value of 'standard' by using the role variable 'sap_hana_install_install_execution_mode'. See the file `defaults/main.yml` of this role.
Solves issue #894.
> sap_hana_install: Set the install execution mode to 'optimized'

- roles/sap_ha_pacemaker_cluster/vars/redhat.yml
- Correction of release in repo name, otherwise this fails on anything later than RHEL 8.
- From RHEL 9 on the azure-lb RA is in a separate package. The same fix was already applied for AWS previously.
> sap_ha_pacemaker_cluster: fixes for RHEL on MS Azure

- roles/sap_ha_install_anydb_ibmdb2/tasks/db2_hadr_enable.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_nwas_common.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/preconfigure_cloud_gcp_ce_vm.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/preconfigure_cloud_ibmcloud_vs.yml
**ansible-lint**
- Jinja whitespace fixes
- noqa added to one task in role `sap_ha_install_anydb_ibmdb2` that includes tabs in the code on purpose
**haproxy config fix (GCP and IBM Cloud VS)**
RHEL: in haproxy 2.4.17 the default systemd service unit was enhanced with an auto-include of the default config file directory using the CFGDIR variable. When creating the unit template for the resources, our role replaced the *Environment* definition and the CFGDIR variable definition was removed, but not the newly added `-f $CFGDIR` in the various *Exec* lines. This broke the start of the unit and resources.
The solution in this PR changes the replaced patterns in the config to make sure the CFGDIR pieces are removed on all lines.
Original excerpt of the unit file section:
```
[Service] …
```
> sap_ha_pacemaker_cluster: Fix haproxy and minor lint issues

- roles/sap_hana_preconfigure/vars/RedHat_9.0.yml
... because HANA 2.0 SPS08 (GCC13 based) has only been validated by SAP starting with RHEL 9.2
Fixes issue #901.
> sap_hana_preconfigure: Do not install compat-sap-c++-13 on RHEL 9.0

- roles/sap_install_media_detect/files/tmp/sapfile
Fixes issue #912.
The SAP Solution Manager JAVA Export file (e.g. 51054655_4.zip) contains files with the search pattern for 'sap_export_nwas_java' before files with the search pattern for 'sap_export_solman_java'. So we do no longer exit for the search pattern of the SAP Netweaver Java files (e.g. 51055106.zip). This will work as long as such files do not have content which are matched by any other search pattern.
Tested with:
- `51050829_3` (NW 7.5 Installation Export)
- `51054655_1` (SAP Solution Manager 7.2 SR2 Installation Export I)
- `51054655_2` (SAP Solution Manager 7.2 SR2 Installation Export II)
- `51054655_4` (SAP Solution Manager 7.2 SR2 - Java)
- `51055106`   (SAP Netweaver 7.5 SP22 Java)
```
$ sapfile *.zip
51050829_3.zip:                          sap_export_nwas_abap …
```
> sap_install_media_detect: Fix wrong sap_export_solman_java detection

- roles/sap_swpm/templates/inifile_params.j2
> sap_swpm: Use 'false' instead of 'False' in inifile.params

- roles/sap_general_preconfigure/defaults/main.yml
- roles/sap_general_preconfigure/tasks/sapnote/2002167/03-setting-the-hostname.yml
- roles/sap_general_preconfigure/tasks/sapnote/2772999/03-configure-hostname.yml
- roles/sap_general_preconfigure/tasks/sapnote/3108316/03-configure-hostname.yml
- roles/sap_swpm/defaults/main.yml
- roles/sap_swpm/tasks/pre_install/update_etchosts.yml
- Add variables for setting collection name to remove hardcode dependency.
- Affected: `sap_swpm` and `sap_general_preconfigure` for calling `sap_maintain_etc_hosts`
Change was tested on SLES4SAP 15 SP6 on AWS with SAP ASCS/ERS HA build.
> sap_swpm, sap_general_preconfigure: feat: add variables for sap_install collection name for calling roles

- roles/sap_swpm/tasks/pre_install/generate_inifile.yml
> sap_swpm: Use master password only when necessary

- roles/sap_ha_pacemaker_cluster/README.md
- roles/sap_ha_pacemaker_cluster/meta/argument_specs.yml
- roles/sap_ha_pacemaker_cluster/tasks/Suse/pre_steps_hana.yml
- roles/sap_ha_pacemaker_cluster/vars/SLES_16.yml
- roles/sap_ha_pacemaker_cluster/vars/Suse.yml
- `pre_steps_hana.yml` was updated with new logic to:
- Angi: Uninstall `SAPHanaSR` only on SLES 15
- Classic: Uninstall `SAPHanaSR-angi` only on SLES 15
- `SLES_16` variables with updated packages
Successfully tested on SLES4SAP 15 SP6 on AWS with SAP HANA HA scenario:
- Angi setup was followed by Classic to test if package uninstall works, then Angi again
> sap_ha_pacemaker_cluster/SUSE: Rework SAPHanaSR-angi pre-steps and add SLES 16 vars

- roles/sap_general_preconfigure/defaults/main.yml
- roles/sap_general_preconfigure/meta/argument_specs.yml
- roles/sap_swpm/defaults/main.yml
I added the missing entry in `sap_general_preconfigure/meta/argument_specs.yml` and slightly modified the variable description.
> sap_swpm, sap_general_preconfigure: Fix some leftovers from #925

- roles/sap_ha_pacemaker_cluster/tasks/RedHat/pre_steps_nwas_ascs_ers.yml
- roles/sap_ha_pacemaker_cluster/tasks/include_vars_nwas.yml
- roles/sap_ha_pacemaker_cluster/vars/RedHat.yml
- Simple-Mount is enabled by default
- Netweaver pre-steps check the resource agents package version and disable Simple-Mount if the defined minimum version is not available
Tested with different package versions available.
The pre-step check overrules custom vars.
> sap_ha_pacemaker_cluster: enable Simple Mount on RHEL

- roles/sap_general_preconfigure/tasks/sapnote/2369910.yml
- roles/sap_ha_pacemaker_cluster/tasks/main.yml
Fixes issue #934.
Note: I also moved the `when:` lines to the end of the task `Configure an English locale` to match our current standard. For `Get the current default locale`, I moved changed_when to the end because that appears to be our default as well.
> sap_general_preconfigure: Fix check mode

- roles/sap_general_preconfigure/vars/RedHat_7.yml
I am not aware of any issues related to missing English locales on RHEL 7, so we can safely assume that a RHEL 7 system will have all necessary English locale packages installed as part of installing the mandatory software environment group.
> sap_general_preconfigure: No longer install locale packages in RHEL 7

- roles/sap_netweaver_preconfigure/README.md
- roles/sap_netweaver_preconfigure/meta/argument_specs.yml
- roles/sap_netweaver_preconfigure/vars/main.yml
Solves #939.
Also moved sap_netweaver_preconfigure_packages to a similar place as in the other preconfigure roles and added this variable to README.md
> sap_netweaver_preconfigure: fix argument_specs validation error

- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_common.yml
- roles/sap_ha_pacemaker_cluster/vars/RedHat.yml
- roles/sap_ha_pacemaker_cluster/vars/main.yml
@marcelmamula @ja9fuchs 
I've found a few regressions in 1.5.0 (or current dev branch) which broke the role when executing on bare metal or vmware systems. I see most changes which caused this are related to cloud systems. This PR  should fix both known errors (another error has been fixed in the current dev branch).
> sap_ha_pacemaker_cluster: Regressions in Dev version for vmware/bare-metal deployments

- roles/sap_general_preconfigure/vars/SLES_SAP_16.yml
ansible-lint complained about this:
```
var-naming[no-role-prefix]: Variables names from within roles should use sap_general_preconfigure_ as a prefix. (vars: __sap_hana_preconfigure_use_saptune)
roles/sap_general_preconfigure/vars/SLES_SAP_16.yml:32
```
> sap_general_preconfigure: fix var role prefix

- roles/sap_ha_pacemaker_cluster/tasks/RedHat/pre_steps_hana.yml
The task return code was incorrect due to disabling `failed_when` entirely.
The new conditions should fix that.
> sap_ha_pacemaker_cluster: fix package detection on RHEL

- roles/sap_general_preconfigure/tasks/SLES/generic/saptune_install.yml
- roles/sap_hana_preconfigure/tasks/SLES/generic/saptune_install.yml
- roles/sap_netweaver_preconfigure/tasks/SLES/generic/saptune_install.yml
Some older images contain older saptune version `3.1.2` which will not be upgraded to latest with `present` state.
This change is ensuring actual latest package version is installed, which then helps with subsequent verification steps (example: kernel.pid_max works different on `3.1.2` versus `3.1.4`)
Validated on SLES4SAP 15 SP6 on AWS:
- PAYG with saptune `3.1.2`
- BYOS with saptune `3.1.4`
> sap_*_preconfigure/Suse: Switch saptune from present to latest

- roles/sap_hana_preconfigure/tasks/RedHat/generic/configure-thp.yml
- roles/sap_hana_preconfigure/tasks/sapnote/2382421.yml
> sap_hana_preconfigure: fix check mode in two tasks

- roles/sap_hana_preconfigure/tasks/sapnote/2055470.yml
> sap_hana_preconfigure: Fix check mode for largesend.conf - ppc64le

- roles/sap_ha_pacemaker_cluster/tasks/ascertain_sap_landscape.yml
- roles/sap_ha_pacemaker_cluster/tasks/configure_nwas_abap_ascs_ers_post_install.yml
- roles/sap_ha_pacemaker_cluster/tasks/configure_nwas_java_scs_ers_post_install.yml
- roles/sap_ha_pacemaker_cluster/tasks/main.yml
Fixes issues #961 and #962.
1. When using the systemd start framework for SAP instances, the instance services must be registered on all nodes they are going to run on. This creates the systemd units consistently.
2. When using the SAPStartSrv resource, the related systemd units 'sapping' and 'sappong' must be enabled.
+ For convenience: tags added to enable role execution just for the NWAS post-installation tasks.
_Tested on RHEL_
> sap_ha_pacemaker_cluster: fix ASCS/ERS systemd

- roles/sap_ha_pacemaker_cluster/tasks/RedHat/pre_steps_nwas_ascs_ers.yml
- roles/sap_ha_pacemaker_cluster/tasks/ascertain_sap_landscape.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_stonith.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_vip_constraints_hana.yml
- roles/sap_ha_pacemaker_cluster/tasks/main.yml
- roles/sap_ha_pacemaker_cluster/vars/hana_scaleup_perf.yml
A few bugs started showing during new tests and need fixing.
The combination of fixes was tested on AWS using
- RHEL 9.4
- HANA scale-up combined with NWAS ASCS/ERS on 2 nodes
- This is a regression introduced in my previous stonith change. :/
During the previous change of the stonith code a conditional was removed that did not apply to the GCP default, but is required for other platform default stonith resources that use host maps.
Fixed a conditional that failed in check-mode. The .stout var is always defined, but can be empty and that fails the version comparison in the last conditional.
- This issue comes up due to the combination of HANA resources with NW groups.
This fixes the HANA VIP colocation constraint conditional to always apply the base score and recalculate only when …
> sap_ha_pacemaker_cluster: several bug fixes

- roles/sap_ha_pacemaker_cluster/tasks/main.yml
For some reason the LSR collection variable is in the way of the ansible syntax-check of some tools, when the task that calls the ha_cluster LSR uses `import_role`.
The same syntax works without errors when the task uses `include_role` instead.
Fixes galaxy-importer error "internal-error: Unexpected error code 1".
> sap_ha_pacemaker_cluster: fix internal-error

- roles/sap_swpm/README.md
Fixes #969.
This PR replaces the original fix provided by SunnyCrockett in https://github.com/sap-linuxlab/community.sap_install/pull/968, as that one contained additional commits.
> sap_swpm: Fix link in README.md

- .ansible-lint
- roles/sap_hostagent/defaults/main.yml
- roles/sap_hostagent/tasks/config_ssl.yml
- **collection**: added `.ansible/` to excludes, this is auto-created by pre-commit and contains the collection, on which the role excludes do not work
- **sap_hostagent**: removed `ansible_become` from defaults, it does not belong in the role but in the playbook, and it triggers the no-role-prefix rule
- **sap_hostagent**: changed some truthy values for consistency
- **sap_hostagent** is now free of linter errors and included in checks
> collection and sap_hostagent: ansible-lint fixes

- roles/sap_general_preconfigure/tasks/sapnote/3562909.yml
- roles/sap_general_preconfigure/tasks/sapnote/assert-3562909.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3562919.yml
- roles/sap_hana_preconfigure/tasks/sapnote/assert-3108302.yml
- roles/sap_hana_preconfigure/tasks/sapnote/assert-3562919.yml
> sap*preconfigure: Use correct RHEL versions in task names

- CHANGELOG.rst
- changelogs/changelog.yaml
In this commit, the file `changelogs/changelog.yml` is being reformatted, to comply with the standards as published in
https://github.com/ansible-community/antsibull-changelog/blob/main/docs/changelogs.md and
https://github.com/ansible-community/antsibull-changelog/blob/main/docs/changelog.yaml-format.md .
The command:
```
antsibull-changelog lint-changelog-yaml changelogs/changelog.yaml
```
returns with return code 0.
The command:
```
antsibull-changelog generate
```
generates the file `CHANGELOG.rst` from file `changelogs/changelog.yaml`. The file `CHANGELOG.rst` is also part of this commit.
Note: The subsections under `changes:` reflect the semver versioning scheme and try to follow the section descriptions in https://github.com/ansible-community/antsibull-changelog/blob/main/docs/chang …
> collection: Cleanup the changelog(s)

- roles/sap_general_preconfigure/tasks/sapnote/2578899/configuration.yml
- roles/sap_hana_preconfigure/tasks/SLES/configuration.yml
- roles/sap_hana_preconfigure/tasks/sapnote/2684254/configuration.yml
- roles/sap_netweaver_preconfigure/tasks/SLES/configuration.yml
PR https://github.com/sap-linuxlab/community.sap_install/pull/930 has introduced new way of handling `saptune` workflow, but it has shown new edge case where:
1. `sap_general_preconfigure` saptune applies sap note `2578899`
2. `sap_hana_preconfigure`: saptune applies solution HANA which already contains `2578899`
3. `sap_hana_preconfigure`: saptune verification of solution HANA fails, because: Application of solution skipped note `2578899`, which was older version, resulting in return code 1 in verification.
It is recommended to always revert saptune before applying solutions and this PR is handling that. 
This issue appeared on Cloud PAYG instances and this PR was tested on AWS and AZ with SLES4SAP 15 SP6, which had issue before.
> sap_*_preconfigure/Suse: Enhance saptune revert logic

- roles/sap_general_preconfigure/tasks/RedHat/generic/assert-etc-hosts.yml
- roles/sap_maintain_etc_hosts/tasks/update_host_present.yml
... in column 1 of /etc/hosts lines.
Solves issue #132.
> sap_general_preconfigure, sap_maintain_etc_hosts: Ignore comments

- roles/sap_swpm/templates/inifile_params.j2
The lines for HDB_Schema_Check_Dialogs.schemaPassword and storageBasedCopy.hdb.systemPassword were within the credentials_hana section and again directly below it. I removed the duplicate outside the section.
> sap_swpm: removed duplicates from credentials_hana section

- roles/sap_ha_pacemaker_cluster/tasks/RedHat/pre_steps_hana.yml
- roles/sap_ha_pacemaker_cluster/tasks/RedHat/pre_steps_nwas_ascs_ers.yml
- roles/sap_ha_pacemaker_cluster/tasks/Suse/post_steps_nwas_abap_ascs_ers.yml
- roles/sap_ha_pacemaker_cluster/tasks/Suse/post_steps_nwas_java_scs_ers.yml
- roles/sap_ha_pacemaker_cluster/tasks/configure_nwas_abap_ascs_ers_post_install.yml
- roles/sap_ha_pacemaker_cluster/tasks/configure_nwas_java_scs_ers_post_install.yml
- roles/sap_ha_pacemaker_cluster/tasks/configure_srhook.yml
- roles/sap_ha_pacemaker_cluster/tasks/main.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/ascertain_platform_type.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/preconfigure_cloud_gcp_ce_vm.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/preconfigure_cloud_ibmcloud_vs.yml
- roles/sap_ha_pacemaker_cluster/tasks/pre_steps_nwas_cs_ers.yml
The check-mode was inconsistent and some of it only surfaced on fresh nodes with no previous cluster config yet.
Check-mode handling has been added to various tasks in different ways:
- `shell/command` tasks with no changes are executed, e.g. for discovering facts
- tasks that should never run in check-mode are skipped explicitly
- tasks that fail in check-mode ignore the failure - it is still useful to see what would be done
The last point especially concerns the `ha_cluster` role include. The entire include will be executed, but since the role is not check-mode safe, it will display the ignored errors. This way it is possible to see the workflow and review it as much as possible before the actual execution.
- RHEL 9.4 on GCP
- RHEL 9.4 on AWS
- HANA scale-up
- NWAS ASCS/ERS
- fresh …
> sap_ha_pacemaker_cluster: fix(check-mode)

- roles/sap_hana_install/tasks/post_install.yml
- roles/sap_hana_install/tasks/pre_install.yml
- Add missing conditionals for `fapolicyd` related tasks that can run only on system where `fapolicyd` is supported.
- `fapolicyd` is not available or supported on SLES.
- Limiting `fapolicyd` tasks removes need to install `python3-rpm` on SLES in order to allow execution of `ansible.builtin.package_facts` which requires higher python version.
> sap_hana_install: Update fapolicyd conditionals

- roles/sap_hana_preconfigure/vars/SLES_15.yml
- roles/sap_hana_preconfigure/vars/SLES_SAP_15.yml
- roles/sap_hana_preconfigure/vars/SLES_SAP_16.yml
- Package `libltdl7` is required for SAP HANA installation on SLES, but it is only preinstalled on Cloud images. This change adds it to list of required packages to be installed for `sap_hana_preconfigure` role.
- Tested on SLES4SAP 15 SP6 on AWS and local VM.
[2998886 - SAP HANA DB installation fails with "hdbnsutil: error while loading shared libraries"](https://me.sap.com/notes/3029056)
[3029056 - Error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory](https://me.sap.com/notes/2998886)
> sap_hana_preconfigure/SLES: Add package libltdl7 to vars

- roles/sap_general_preconfigure/README.md
- roles/sap_general_preconfigure/defaults/main.yml
- roles/sap_general_preconfigure/meta/argument_specs.yml
- roles/sap_general_preconfigure/tasks/SLES/configuration.yml
1. Add support for `/etc/hosts` changes to SUSE configuration steps, same as done in RedHat steps.
2. Update `sap_general_preconfigure_domain` comments to correctly spell out how mandatory it is.
3. Rename readme variables to correctly represent role variables.
Tested on SLES4SAP 15 SP6 on AWS and Local VM where `sap_general_preconfigure_domain` is mandatory because `ansible_domain` is undefined (requires `/etc/hosts` first).
> sap_general_preconfigure/SLES: Add etc hosts setup to configure steps

- roles/sap_swpm/templates/inifile_params.j2
... from `templates/inifile_params.j2`
Solves #985. See also PR #982.
> sap_swpm: remove duplicate section `credentials_anydb_ibmdb2`

- roles/sap_general_preconfigure/tasks/RedHat/generic/configure-kernel-parameters.yml
- roles/sap_hana_preconfigure/tasks/sapnote/2055470.yml
- roles/sap_hana_preconfigure/tasks/sapnote/2382421.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3024346.yml
Hi @berndfinger,
PR#807 introduced checks of kernel parameters to support indepotency.
However, under very rare circumstances when the sysctl conf files contain comments (#) this check fails as the awk command includes the line with the comments as a kernel parameter to check.
It generates something like:
```sysctl #This is comment net.ipv4.tcp_rmem```
This PR makes a minor change to make awk exclude all lines starting with # (i.e. ^#).
Kudos @James-Allen_nbs.
> sap*preconfigure: sysctl checks fail when config file has comments

- galaxy.yml
Fix for link https://github.com/sap-linuxlab/sap-linuxlab.github.io/blob/master/README.md in galaxy documentation, which does not contain any documentation.
Correct link: https://github.com/sap-linuxlab/community.sap_install/blob/main/README.md
> Collection: fix documentation link in galaxy.yml

- roles/sap_swpm/README.md
The selinux role is not called from sap_swpm, so the Dependencies section in README.md needs to be empty.
> sap_swpm: Remove selinux role dependency from README.md

- roles/sap_hana_install/README.md
- roles/sap_hana_install/defaults/main.yml
- roles/sap_hana_install/tasks/post_install.yml
I have some central managed users and I'm not able to change them. This option would allow the playbook not to fail in this step.
> sap_hana_install: Add opt-out for setting sidadm to noexpire 

- roles/sap_swpm/README.md
- roles/sap_swpm/defaults/main.yml
- roles/sap_swpm/tasks/post_install.yml
I've central managed users and the ansible code should be able to not run the changes to the linux users.
> sap_swpm: Add opt-out for setting sidadm to noexpire

- roles/sap_swpm/tasks/pre_install/generate_inifile.yml
- roles/sap_swpm/tasks/pre_install/swpm_prepare.yml
Solves issue #1023.
Also display the full path name of the inifile in a separate task, similar to the role sap_hana_install.
> sap_swpm: Require inifile.params only on the managed node when re-using an existing inifile.params.

- roles/sap_ha_pacemaker_cluster/tasks/Suse/pre_steps_hana.yml
Remove dependency on `python3-rpm` that is needed for `ansible.builtin.package_facts`.
This was already done for other preconfigure roles as well as `ha_cluster` in LSR.
@berndfinger It would be good to remove it also from  `sap_swpm` firewall tasks, but that can be done separately.
> sap_ha_pacemaker_cluster/SUSE: Remove python3-rpm dependency in pre_steps_hana

- roles/sap_storage_setup/tasks/generic_tasks/configure_nfs_filesystems.yml
We are using `/software` as preferred software location in playbooks and most of our roles, so it makes sense to actually allow its mounting using role.
This will allow following simple adjustment to mount software without downloading:
```yaml
storage_definition:
- name: software
mountpoint: /software
nfs_path: ''
nfs_server: "{{ sap_vm_provision_nfs_mount_point | default('') }}"
nfs_filesystem_type: "{{ sap_vm_provision_nfs_mount_point_type | default('') }}"
nfs_mount_options: "{{ sap_vm_provision_nfs_mount_point_opts | default('') }}"
```
This parameter results in behavior that does not align well with using NFS mount as source as it would create unnecessary subfolder. Keeping it empty will result in desired behavior.
> sap_storage_setup: Allow /software NFS mount

- roles/sap_general_preconfigure/tasks/SLES/generic/saptune_takeover.yml
- roles/sap_general_preconfigure/vars/SLES_15.yml
- roles/sap_general_preconfigure/vars/SLES_SAP_15.yml
- roles/sap_general_preconfigure/vars/SLES_SAP_16.yml
- roles/sap_hana_preconfigure/tasks/SLES/generic/saptune_takeover.yml
- roles/sap_hana_preconfigure/vars/SLES_15.yml
- roles/sap_hana_preconfigure/vars/SLES_SAP_15.yml
- roles/sap_hana_preconfigure/vars/SLES_SAP_16.yml
- roles/sap_netweaver_preconfigure/tasks/SLES/generic/saptune_takeover.yml
- roles/sap_netweaver_preconfigure/vars/SLES_SAP_16.yml
- Update SLES 16 pattern name
- Add `lsof` and `libltdl7` into dependencies for hardened images.
- Update saptune takeover steps to skip for SLES16, where sapconf is not present.
> sap_*_preconfigure/SUSE: Update SLES16 pattern names and add packages for hardened images

- roles/sap_ha_pacemaker_cluster/tasks/Suse/post_steps_hana_scaleup.yml
- SAP HANA post steps restructured to ensure that each step is executed when SAP HANA is idle and it does not fail.
- Steps were split for Angi and non-Angi
Cluster was tested on SLES 15 SP6 and SLES 16 RC1.
First command `cs_wait_for_idle -s 5` takes around 5 minutes while SAP HANA Is starting, then subsequent commands are quick.
> sap_ha_pacemaker_cluster/SUSE: SAP HANA scaleup post steps updated

- roles/sap_ha_pacemaker_cluster/README.md
- roles/sap_ha_pacemaker_cluster/meta/argument_specs.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_vip_resources_default.yml
- roles/sap_ha_pacemaker_cluster/tasks/include_vars_common.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/construct_vars_vip_resources_cloud_aws_ec2_vs.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/construct_vars_vip_resources_cloud_gcp_ce_vm.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/construct_vars_vip_resources_cloud_ibmcloud_powervs.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/construct_vars_vip_resources_hyp_ibmpower_vm.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/register_sysinfo_cloud_ibmcloud_powervs.yml
- roles/sap_ha_pacemaker_cluster/vars/main.yml
`IPaddr2` resource agent does not require parameter `nic` when cluster node has only 1 network interface (2 if loopback is counted). This means we do not need to populate it unless required.
- Add conditional `attrs` creation, which will include `nic` parameter only if it is user defined.
- Replace default NIC assignment with internal variable `__sap_ha_pacemaker_cluster_vip_client_interface` that will run only if user did not specify `sap_ha_pacemaker_cluster_vip_client_interface`, but it is consumed only when required.
- Remove multi NIC variable `__sap_ha_pacemaker_cluster_nic_multi_bool` as it was not used.
- Update Readme with explanation.
**NOTE:** This change does not affect Google Cloud, as their documentation explicitly mentions `nic` parameter.
This change was tested on:
SLES 15 …
> sap_ha_pacemaker_cluster: Remove NIC parameter from IPaddr2 resource agents

- roles/sap_ha_pacemaker_cluster/README.md
- roles/sap_ha_pacemaker_cluster/defaults/main.yml
- roles/sap_ha_pacemaker_cluster/meta/argument_specs.yml
- roles/sap_ha_pacemaker_cluster/tasks/configure_nwas_abap_ascs_ers_post_install.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_common.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_nwas_abap_ascs_ers_simple_mount.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_stonith.yml
- roles/sap_ha_pacemaker_cluster/tasks/include_vars_hana.yml
- roles/sap_ha_pacemaker_cluster/vars/RedHat.yml
- roles/sap_ha_pacemaker_cluster/vars/Suse.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_aws_ec2_vs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_gcp_ce_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_msazure_vm.yml
1. Post steps for ASCS/ERS were not restarting correct cluster resources, resulting in empty output of `HAGetFailoverConfig` because Sapstartsrv was not loaded with cluster connector.
2. Cluster properties for stonith were not correct and ASCS parameter was missing.
- ASCS/ERS Post tasks
- Reorganize existing tasks (@ja9fuchs This will cause some mess with git diff, so please check it directly in fork)
- Replace restart Sapstartsrv with restart of resource group so it can manage all resources
- Add blocks around tasks with same parameters to simplify code
- Cluster properties
- Remove default variable `sap_ha_pacemaker_cluster_cluster_properties` to enable proper loading of user defined versus predefined.
- Remove defaults for `concurrent-fencing` because it is used only by HANA Scaleout …
> sap_ha_pacemaker_cluster: Enhance handling of cluster properties and improve ASCS ERS post steps

- .gitignore
- roles/sap_general_preconfigure/handlers/main.yml
- roles/sap_general_preconfigure/tasks/sapnote/2369910.yml
- roles/sap_ha_pacemaker_cluster/tasks/configure_nwas_abap_ascs_ers_post_install.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_common.yml
- roles/sap_ha_pacemaker_cluster/tasks/main.yml
- roles/sap_ha_pacemaker_cluster/tasks/pre_steps_nwas_cs_ers.yml
- roles/sap_hana_install/defaults/main.yml
- roles/sap_hana_preconfigure/handlers/main.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-thp.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/configure-thp.yml
- roles/sap_maintain_etc_hosts/tasks/update_host_absent.yml
- roles/sap_maintain_etc_hosts/tasks/update_host_present.yml
- roles/sap_netweaver_preconfigure/handlers/main.yml
- roles/sap_storage_setup/tasks/generic_tasks/configure_nfs_filesystems.yml
- roles/sap_storage_setup/tasks/generic_tasks/configure_swap.yml
Details about upcoming ansible-core 2.19 are listed in https://github.com/sap-linuxlab/community.sap_install/issues/1101
- Add conditionals where truthy was attempted against non-boolean variables
- Add checks for `none` or `type_debug` when required.
- Add condition to all `regex_search` in when checks, because they return `NoneType` which is not truthy (This is not an issue inside of `set_fact`).
**NOTE 1: Dictionary assignments have to be carefully tested because `2.19` now marks them as `string`, invalidating lot of code.**
**NOTE 2: Changes to role `sap_swpm` are prepared and waiting for https://github.com/sap-linuxlab/community.sap_install/pull/1067 to be completed first.**
Latest commit was tested on `ansible-core 2.16 2.18 2.19` targeting SLES 15 SP6 on AWS and SLES 16 on premise.
> collection: Adjust roles for ansible-core 2.19 part 1

- roles/sap_swpm/defaults/main.yml
- roles/sap_swpm/tasks/pre_install.yml
- roles/sap_swpm/tasks/pre_install/assert_vars_length_loop_block.yml
- roles/sap_swpm/tasks/pre_install/detect_variables_from_inifile.yml
- roles/sap_swpm/tasks/pre_install/generate_inifile.yml
- roles/sap_swpm/tasks/pre_install/install_type.yml
- roles/sap_swpm/tasks/pre_install/prepare_software.yml
- roles/sap_swpm/templates/inifile_params.j2
Main changes in this PR:
- All variables in `defaults/main.yml` are now defined, typically with an empty string.
- Some long comments in `defaults/main.yml` are rearranged to shorten the line length.
- In `tasks/pre_install.yml`, we are now detecting early if an inifile exists at location
`{{ sap_swpm_inifile_directory }}/inifile.params`.
This allows for the early detection of the 4 essential role variables:
- `sap_swpm_software_path`
- `sap_swpm_product_catalog_id`
- `sap_swpm_sid`
- `sap_swpm_fqdn`
- We are now validating all role parameters (as contained in the section `# Following variables are defined and
validated:` of the Ansible Playbooks for SAP and as used in the inifile sections defined under `sap_swpm_inifile_sections_list` in all files named `ansible_extravars.yml`), using …
> sap_swpm: extensive variable input validation

- roles/sap_hana_install/.ansible-lint
- roles/sap_hana_install/README.md
- roles/sap_hana_install/tasks/hana_exists.yml
- roles/sap_hana_install/tasks/hana_start.yml
- roles/sap_hana_install/tasks/main.yml
- roles/sap_hana_install/tasks/post_install.yml
- roles/sap_hana_install/tasks/post_install/check_installation.yml
- roles/sap_hana_install/tasks/post_install/fapolicyd.yml
- roles/sap_hana_install/tasks/post_install/hdbuserstore.yml
- roles/sap_hana_install/tasks/post_install/log_mode.yml
- roles/sap_hana_install/tasks/post_install/recreate_tenant_database.yml
- roles/sap_hana_install/tasks/pre_install.yml
- roles/sap_hana_install/tasks/pre_install/hdblcm_configfile.yml
- roles/sap_hana_install/tasks/pre_install/hdblcm_prepare.yml
- roles/sap_hana_install/tasks/pre_install/verify_checksum.yml
This is pull request to improve idempotency that was causing issues, for example https://github.com/sap-linuxlab/community.sap_install/issues/1050
Plan that was agreed on for both `sap_hana_install` and `sap_swpm`:
- Separate installation and configuration tasks to ensure that configuration tasks are always executed.
- Use detection to set Boolean variable that will decide execution of installation and configuration tasks.
- Retain detection logic and use `__sap_hana_install_fact_is_installed` to separate installation and configuration tasks
- Rework `post_install` steps:
- Carve out modular tasks into separate task files
- Reorder to installation block and configuration steps
- New final debug message for post_install configuration tasks
- Miscellaneous linting fixes, but not full …
> sap_hana_install: Idempotency Rework

- roles/sap_hana_install/README.md
- roles/sap_hana_install/tasks/assert-addhosts-loop-block.yml
- roles/sap_hana_install/tasks/assert_variables.yml
- roles/sap_hana_install/tasks/hana_addhosts.yml
- roles/sap_hana_install/tasks/hana_exists.yml
- roles/sap_hana_install/tasks/main.yml
- roles/sap_hana_install/tasks/pre_install.yml
Several combinations of input variables resulted in skipped tasks in certain conditions, or on other hand executed tasks that should not have been.
Following scenarios were accounted for:
| Scenario | exists | start | pre_install | install | addhosts | post_install |
| --- | --- | --- | --- | --- | --- | --- |
| (1) New install one host | :white_check_mark: | :x: | :white_check_mark: | :white_check_mark: | :x: | :white_check_mark: |
| (2) Repeat install one host | :white_check_mark: | :white_check_mark: | :x: | :x: | :x: | :white_check_mark: |
| (3) New install scaleout | :white_check_mark: | :x: | :white_check_mark: | :white_check_mark: | :x: | :white_check_mark: |
| (4) Repeat install scaleout | :white_check_mark: | :white_check_mark: | :x: | :x: | :x: | :white_check_mark: |
| (5) Add …
> sap_hana_install: Enhance variable validation and account for missed variable combinations

- roles/sap_ha_pacemaker_cluster/tasks/construct_final_hacluster_vars.yml
- roles/sap_ha_pacemaker_cluster/tasks/pre_steps_nwas_cs_ers.yml
Fixes for `ansible-lint` that is updated as part of https://github.com/sap-linuxlab/community.sap_install/pull/1118
- `sap_ha_pacemaker_cluster_instance_service_all_fact` defaulted to `[]` to fix `jinja[invalid]: Error rendering template: can only concatenate list (not "UndefinedMarker") to list`
- `# noqa var-naming[no-role-prefix]` added to all tasks setting `ha_cluster` variables, because using .ansible-lint-ignore will show it as warnings, polluting log.
```bash
ansible-lint --version
ansible-lint 25.9.0 using ansible-core:2.19.2 ansible-compat:25.8.1 ruamel-yaml:0.18.14 ruamel-yaml-clib:0.2.12
ansible-lint roles/sap_ha_pacemaker_cluster/
Failed: 20 failure(s), 0 warning(s) in 78 files processed of 80 encountered.
Passed: 0 failure(s), 0 warning(s) in 78 files processed of 80 …
```
> sap_ha_pacemaker_cluster:: Fix linting errors
