sap-linuxlab/community.sap_install

- .github/workflows/pylint.yml
I think we do not need automated workflow for pylint at the moment. Not much py code.
> Pylint - manual workflow

- .github/workflows/yamllint-sap_general_preconfigure.yml
- .github/workflows/yamllint-sap_hana_install.yml
- .github/workflows/yamllint-sap_hana_preconfigure.yml
- .github/workflows/yamllint-sap_netweaver_preconfigure.yml
Yaml lint workflows for following roles
sap_general_preconfigure
sap_hana_install
sap_hana_preconfigure
sap_netweaver_preconfigure
> Yaml lint workflows

- roles/sap_hana_install/tasks/pre_install.yml
- roles/sap_hana_install/tasks/pre_install/extract_sar.yml
- roles/sap_hana_install/tasks/pre_install/hdblcm_prepare.yml
> sap_hana_install: Bugfix for Issue #50 

- roles/sap_general_preconfigure/meta/main.yml
- roles/sap_general_preconfigure/tasks/RedHat/generic/configure-selinux.yml
- roles/sap_general_preconfigure/tasks/RedHat/installation.yml
- roles/sap_hana_install/meta/main.yml
- roles/sap_hana_install/meta/runtime.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-cpu-governor-for-performance.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/configure-cpu-governor-for-performance.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/configure-epb.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/configure-tuned.yml
- roles/sap_hana_preconfigure/tasks/RedHat/installation.yml
- roles/sap_hana_preconfigure/tasks/sapnote/2055470.yml
- roles/sap_hana_preconfigure/tasks/sapnote/2382421.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3024346.yml
- roles/sap_netweaver_preconfigure/meta/main.yml
- roles/sap_netweaver_preconfigure/tasks/sapnote/2526952.yml
> sap*preconfigure: ansible-lint 5.4.0 cleanup (#60)

- roles/sap_general_preconfigure/meta/main.yml
- roles/sap_hana_install/meta/main.yml
- roles/sap_hana_preconfigure/meta/main.yml
- roles/sap_netweaver_preconfigure/meta/main.yml
We have to make the license in meta/main.yml compatible with the licence
of the repository, which is Apache 2.0.
Solves issue #87.
> several roles: Adapt license in meta/main.yml

- .github/workflows/ansible-lint sap_general_preconfigure.yml
- .github/workflows/ansible-lint sap_hana_install.yml
- .github/workflows/ansible-lint sap_hana_preconfigure.yml
- .github/workflows/ansible-lint sap_netweaver_preconfigure.yml
- .github/workflows/ansible-lint.yml
> repository: name change of main branch of ansible-lint-action

- roles/sap_netweaver_preconfigure/tasks/RedHat/assert-configuration.yml
- roles/sap_netweaver_preconfigure/tasks/RedHat/assert-installation.yml
- roles/sap_netweaver_preconfigure/tasks/RedHat/configuration.yml
- roles/sap_netweaver_preconfigure/tasks/RedHat/installation.yml
- roles/sap_netweaver_preconfigure/tasks/SLES/configuration.yml
- roles/sap_netweaver_preconfigure/tasks/SLES/installation.yml
- roles/sap_netweaver_preconfigure/tasks/main.yml
- roles/sap_netweaver_preconfigure/tasks/sapnote/1275776/configuration.yml
- roles/sap_netweaver_preconfigure/tasks/sapnote/1275776/installation.yml
- roles/sap_netweaver_preconfigure/tasks/sapnote/2526952.yml
- roles/sap_netweaver_preconfigure/tasks/sapnote/assert-2526952.yml
- roles/sap_netweaver_preconfigure/vars/SLES_15.yml
Splitted the configuration, installation part as in hana_preconfigure
> add SLES support for NW preconfigure

- roles/sap_swpm/tasks/swpm.yml
> fix swpm install for sles 

- roles/sap_ha_install_hana_hsr/defaults/main.yml
- roles/sap_ha_install_hana_hsr/tasks/configure_firewall.yml
- roles/sap_ha_install_hana_hsr/tasks/configure_hsr.yml
- roles/sap_ha_install_hana_hsr/tasks/hdbuserstore.yml
- roles/sap_ha_install_hana_hsr/tasks/log_mode.yml
- roles/sap_ha_install_hana_hsr/tasks/main.yml
- roles/sap_ha_install_hana_hsr/tasks/pki_files.yml
- roles/sap_ha_install_hana_hsr/tasks/run_backup.yml
- roles/sap_ha_install_pacemaker/defaults/main.yml
- roles/sap_ha_install_pacemaker/tasks/cluster_constraint.yml
- roles/sap_ha_install_pacemaker/tasks/cluster_resources.yml
- roles/sap_ha_install_pacemaker/tasks/cluster_setup.yml
- roles/sap_ha_install_pacemaker/tasks/cluster_srhook.yml
- roles/sap_ha_install_pacemaker/tasks/cluster_sudoer.yml
- roles/sap_ha_install_pacemaker/tasks/main.yml
- roles/sap_ha_install_pacemaker/tasks/preconfig.yml
- roles/sap_ha_install_pacemaker/tasks/software_setup.yml
- roles/sap_ha_install_pacemaker/tasks/stonith_config.yml
- roles/sap_ha_set_hana/defaults/main.yml
- roles/sap_ha_set_hana/tasks/cluster_constraint.yml
- roles/sap_ha_set_hana/tasks/cluster_resources.yml
- roles/sap_ha_set_hana/tasks/cluster_srhook.yml
- roles/sap_ha_set_hana/tasks/cluster_sudoer.yml
- roles/sap_ha_set_hana/tasks/main.yml
- roles/sap_ha_set_hana/tasks/saphanasr_python_hook.yml
- roles/sap_hana_install/defaults/main.yml
initial pull request for HANA HA HSR
to get the updated system roles
> initial pull request for HANA HA HSR

- roles/sap_hana_install/tasks/hana_addhosts.yml
- roles/sap_hana_install/tasks/hana_exists.yml
- roles/sap_hana_install/tasks/hana_install.yml
- roles/sap_hana_install/tasks/post_install.yml
- roles/sap_swpm/tasks/post_install.yml
- roles/sap_swpm/tasks/pre_install.yml
- roles/sap_swpm/tasks/swpm.yml
Also some changes to internal variable names for sap_swpm and sap_hana_install and a conversion from ".rc == 0" to "is succeeded".
> sap_swpm: Solve issue #183; call sapinst synchronously

- docs/developer_notes/sap_swmp_dev.md
- roles/sap_swpm/templates/configfile.j2
sap_swpm: working java installs
> sap_swpm: working java installs

- .ansible-lint
- roles/sap_swpm/tasks/post_install/firewall.yml
- roles/sap_swpm/tasks/pre_install/install_type/maint_plan_stack_install.yml
Further few linter fixes in role sap_swpm.
> sap_swpm: fixing linter issues and bad jinja

- .ansible-lint
- roles/sap_hana_install/README.md
- roles/sap_hana_install/defaults/main.yml
- roles/sap_hana_install/tasks/hana_exists.yml
- roles/sap_hana_install/tasks/main.yml
- roles/sap_hana_install/tests/install/README.md
> New hana exist check

- roles/sap_ha_pacemaker_cluster/.ansible-lint
- roles/sap_ha_pacemaker_cluster/.yamllint.yml
- roles/sap_ha_pacemaker_cluster/defaults/main.yml
- roles/sap_ha_pacemaker_cluster/tasks/main.yml
Changed the Linux System Role include from role to collection path, in order to align with agreed SAP collection dependency handling.
> sap_ha_pacemaker_cluster: align LSR include with collection requirement

- .ansible-lint
- roles/sap_general_preconfigure/tasks/RedHat/assert-installation.yml
- roles/sap_general_preconfigure/tasks/RedHat/installation.yml
- roles/sap_general_preconfigure/tasks/SLES/assert-installation.yml
- roles/sap_general_preconfigure/tasks/SLES/installation.yml
- roles/sap_hana_preconfigure/tasks/RedHat/assert-installation.yml
- roles/sap_hana_preconfigure/tasks/RedHat/installation.yml
- roles/sap_hana_preconfigure/tasks/sapnote/2292690/10-assert-ibm-energyscale.yml
- roles/sap_netweaver_preconfigure/tasks/RedHat/assert-installation.yml
Solves issue #246, by removing all warn: false arguments from tasks which call the shell and command modules
> preconfigure roles: Prepare for Ansible 2.14

- roles/sap_netweaver_preconfigure/defaults/main.yml
- roles/sap_netweaver_preconfigure/tasks/sapnote/3119751.yml
- roles/sap_netweaver_preconfigure/tasks/sapnote/assert-3119751.yml
- roles/sap_netweaver_preconfigure/vars/RedHat_8.yml
> sap_netweaver_preconfigure: Add link to libstdc++.so.6

- roles/sap_hana_preconfigure/vars/RedHat_8.yml
> sap_hana_preconfigure: Update RHEL 8 repo vars file

- roles/sap_swpm/defaults/main.yml
> sap_swpm: No longer update /etc/hosts by default

- roles/sap_general_preconfigure/vars/RedHat_8.0.yml
- roles/sap_general_preconfigure/vars/RedHat_8.1.yml
- roles/sap_general_preconfigure/vars/RedHat_8.2.yml
- roles/sap_general_preconfigure/vars/RedHat_8.yml
- roles/sap_general_preconfigure/vars/RedHat_9.yml
- roles/sap_hana_preconfigure/tasks/sapnote/2777782/10-assert-pidmax.yml
- roles/sap_hana_preconfigure/tasks/sapnote/2777782/10-increase-pidmax.yml
- roles/sap_hana_preconfigure/vars/RedHat_8.yml
- roles/sap_hana_preconfigure/vars/RedHat_9.yml
> Set kernel.pid_max only on RHEL 8.0 and RHEL 8.1

- roles/sap_swpm/tasks/pre_install/update_etchosts.yml
> sap_swpm: Ensure correct /etc/hosts entries

- roles/sap_hana_install/tasks/hana_exists.yml
- roles/sap_hana_install/tasks/main.yml
Also add one more tag 'sap_hana_install_check_hana_exists' for running all hana_exists checks
> sap_hana_install: Solve issue #273

- roles/sap_swpm/defaults/main.yml
- roles/sap_swpm/templates/configfile.j2
sap_swpm: NWAS AAS fix and prettify params (alphabetical, move commented-out params to bottom of each segment etc).
> sap_swpm: NWAS AAS fix and prettify params

- roles/sap_hana_preconfigure/vars/RedHat_8.yml
- roles/sap_hana_preconfigure/vars/RedHat_9.yml
> sap_hana_preconfigure: IBMinvscout is back

- roles/sap_hana_install/tasks/pre_install/hdblcm_configfile.yml
> sap_hana_install: Explain the logic for creating the hdblcm configfile

- roles/sap_hana_preconfigure/tasks/sapnote/3108302.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/01-assert-selinux.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/01-configure-selinux.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/02-assert-tuned.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/02-configure-tuned.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/03-assert-abrt-coredumps-kdump.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/03-disable-abrt-coredumps-kdump.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/04-assert-auto-numa-balancing.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/04-turn-off-auto-numa-balancing.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/05-assert-thp.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/05-disable-thp.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/06-assert-c-states-for-lower-latency.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/06-configure-c-states-for-lower-latency.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/07-assert-cpu-governor.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/07-configure-cpu-governor.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/08-assert-epb.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/08-configure-epb.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/09-assert-ksm.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/09-disable-ksm.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/10-assert-pidmax.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/10-increase-pidmax.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/11-assert-tsx.yml
- roles/sap_hana_preconfigure/tasks/sapnote/3108302/11-enable-tsx.yml
- roles/sap_hana_preconfigure/tasks/sapnote/assert-3108302.yml
- roles/sap_hana_preconfigure/vars/RedHat_8.yml
- roles/sap_hana_preconfigure/vars/RedHat_9.yml
> sap_hana_preconfigure: sync with recent SAP notes updates for RHEL 9 

- roles/sap_hana_preconfigure/defaults/main.yml
- roles/sap_hana_preconfigure/tasks/RedHat/installation.yml
- roles/sap_hana_preconfigure/vars/RedHat_7.yml
- roles/sap_hana_preconfigure/vars/RedHat_8.yml
- roles/sap_hana_preconfigure/vars/RedHat_9.yml
> sap_hana_preconfigure: Be more flexible with IBM POWER tools

- .github/workflows/ansible-lint-sap_ha_pacemaker_cluster.yml
Testing if this action update fixes the workflow failures.
> gh action update for sap_ha_pacemaker_cluster

- playbooks/sample-storage_sap_s4hana_distributed.yml
- roles/sap_storage_setup/README.md
- roles/sap_storage_setup/defaults/main.yml
- roles/sap_storage_setup/meta/argument_specs.yml
- roles/sap_storage_setup/tasks/main.yml
... and a sample playbook for running the storage setup role.
> sap_storage_setup: updated README and minor improvements

- roles/sap_storage_setup/vars/RedHat.yml
- roles/sap_storage_setup/vars/Suse.yml
> sap_storage_setup: amend pkgs

- .github/workflows/ansible-lint-sap_ha_pacemaker_cluster.yml
- roles/sap_ha_pacemaker_cluster/defaults/main.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_hana_common.yml
- roles/sap_ha_pacemaker_cluster/tasks/main.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/ascertain_platform_type.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/construct_vars_vip_resources_cloud_aws_ec2_vs.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/construct_vars_vip_resources_cloud_msazure_vm.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/include_vars_platform.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/preconfigure_cloud_aws_ec2_vs.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/preconfigure_cloud_ibmcloud_powervs.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/preconfigure_cloud_ibmcloud_vs.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/preconfigure_cloud_msazure_vm.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/register_sysinfo_cloud_ibmcloud_powervs.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/register_sysinfo_cloud_ibmcloud_vs.yml
- roles/sap_ha_pacemaker_cluster/vars/hana_scaleout_common.yml
- roles/sap_ha_pacemaker_cluster/vars/hana_scaleup_common.yml
- roles/sap_ha_pacemaker_cluster/vars/main.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_aws_ec2_vs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_gcp_ce_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_ibmcloud_powervs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_msazure_vm.yml
**New**
- additional cloud platform detection tasks
- more platform variables
**Minor Update**
- standard HANA SR hook path to match RHEL documentation
- SAPHana resource monitor interval values to match RHEL documentation
> sap_ha_pacemaker_cluster: cloud platform updates

- roles/sap_install_media_detect/README.md
- roles/sap_install_media_detect/defaults/main.yml
- roles/sap_install_media_detect/tasks/cleanup/disable-epel-repo.yml
- roles/sap_install_media_detect/tasks/detect_export_sapbw4hana.yml
- roles/sap_install_media_detect/tasks/detect_export_sapecc.yml
- roles/sap_install_media_detect/tasks/detect_export_sapecc_ides.yml
- roles/sap_install_media_detect/tasks/detect_export_sapnwas_abap.yml
- roles/sap_install_media_detect/tasks/detect_export_sapnwas_java.yml
- roles/sap_install_media_detect/tasks/detect_export_saps4hana.yml
- roles/sap_install_media_detect/tasks/detect_export_sapsolman_abap.yml
- roles/sap_install_media_detect/tasks/detect_sapanydb_ibmdb2.yml
- roles/sap_install_media_detect/tasks/detect_sapanydb_oracledb.yml
- roles/sap_install_media_detect/tasks/detect_sapanydb_sapase.yml
- roles/sap_install_media_detect/tasks/detect_sapanydb_sapmaxdb.yml
- roles/sap_install_media_detect/tasks/detect_sapcar.yml
- roles/sap_install_media_detect/tasks/detect_saphana.yml
- roles/sap_install_media_detect/tasks/detect_saphostagent.yml
- roles/sap_install_media_detect/tasks/detect_sapswpm.yml
- roles/sap_install_media_detect/tasks/main.yml
- roles/sap_install_media_detect/tasks/prepare/check_directories.yml
- roles/sap_install_media_detect/tasks/prepare/create_file_list.yml
- roles/sap_install_media_detect/tasks/prepare/enable_rar_handling.yml
- roles/sap_install_media_detect/tasks/rename/add_rar_extension.yml
- roles/sap_install_media_detect/tasks/rename/add_rar_extension_loop_block.yml
- roles/sap_install_media_detect/tasks/set_global_vars.yml
This is the first part of adding NFS support. No change yet in the logic for moving SAP archive files or for expanding files.
> Issue 385: Re-implement rar file renaming; improve rar file handling; add tags

- roles/sap_ha_pacemaker_cluster/tasks/platform/ascertain_platform_type.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/construct_vars_vip_resources_cloud_aws_ec2_vs.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/construct_vars_vip_resources_cloud_ibmcloud_powervs.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/construct_vars_vip_resources_cloud_msazure_vm.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/construct_vars_vip_resources_hyp_ibmpower_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_hyp_ibmpower_lpar.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_hyp_ibmpower_vm.yml
- replaced occurrences of "lpar" with "vm" 
- added VIP construction tasks for IBM Power Virtual Servers from IBM Cloud and IBM PowerVM hypervisor virtual machines
- added platform vars for IBM PowerVM
> sap_ha_pacemaker_cluster: ibmpower updates

- roles/sap_swpm/tasks/swpm/swpm_inifile_generate_inifile_reuse.yml
The awk method with a pattern to not look into comments appears to be the most robust method in this case.
> sap_swpm: Solve issue #353

- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_stonith.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/construct_vars_vip_resources_cloud_gcp_ce_vm.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/preconfigure_cloud_gcp_ce_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_aws_ec2_vs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_gcp_ce_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_ibmcloud_powervs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_ibmcloud_vs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_msazure_vm.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_hyp_ibmpower_vm.yml
- new files for GCP specific tasks
- minor stonith default resource definition adjustment to separate the resource name from the agent name
> sap_ha_pacemaker_cluster: GCP content and stonith defaults adjustment

- CHANGELOG.rst
- README.md
- galaxy.yml
collection: prepare for v1.3.0
> collection: prepare for v1.3.0

- roles/sap_install_media_detect/tasks/set_global_vars.yml
> sap_install_media_detect: Display all facts at the end of the role

- roles/sap_install_media_detect/tasks/detect_backup_saphana.yml
- roles/sap_install_media_detect/tasks/detect_export_sapbw4hana.yml
- roles/sap_install_media_detect/tasks/detect_export_sapecc.yml
- roles/sap_install_media_detect/tasks/detect_export_sapecc_ides.yml
- roles/sap_install_media_detect/tasks/detect_export_sapnwas_abap.yml
- roles/sap_install_media_detect/tasks/detect_export_sapnwas_java.yml
- roles/sap_install_media_detect/tasks/detect_export_saps4hana.yml
- roles/sap_install_media_detect/tasks/detect_export_sapsolman_abap.yml
- roles/sap_install_media_detect/tasks/detect_sapanydb_ibmdb2.yml
- roles/sap_install_media_detect/tasks/detect_sapanydb_oracledb.yml
- roles/sap_install_media_detect/tasks/detect_sapanydb_sapase.yml
- roles/sap_install_media_detect/tasks/detect_sapanydb_sapmaxdb.yml
- roles/sap_install_media_detect/tasks/detect_saphana.yml
... instead of contains.
Also use regex patterns, and use only true/false for booleans in the find tasks.
Solves issue #388
> sap_install_media_detect: use 'patterns' for find

- CHANGELOG.rst
- README.md
- galaxy.yml
- playbooks/vars/sample-variables-sap-swpm-advanced-mode-s4hana-onehost-install.yml
- playbooks/vars/sample-variables-sap-swpm-advanced-templates-mode.yml
- playbooks/vars/sample-variables-sap-swpm-default-mode-bw4hana-onehost-install.yml
- playbooks/vars/sample-variables-sap-swpm-default-mode-s4hana-distributed-ascs-install.yml
- playbooks/vars/sample-variables-sap-swpm-default-mode-s4hana-distributed-dbload-install.yml
- playbooks/vars/sample-variables-sap-swpm-default-mode-s4hana-distributed-ers-install.yml
- playbooks/vars/sample-variables-sap-swpm-default-mode-s4hana-distributed-pas-install.yml
- playbooks/vars/sample-variables-sap-swpm-default-mode-s4hana-onehost-install.yml
- playbooks/vars/sample-variables-sap-swpm-default-mode-s4hana-onehost-restore.yml
- playbooks/vars/sample-variables-sap-swpm-default-mode-solman-hana-abap-onehost-install.yml
- playbooks/vars/sample-variables-sap-swpm-default-mode-solman-hana-java-onehost-install.yml
- playbooks/vars/sample-variables-sap-swpm-default-mode-webdisp-standalone-install.yml
- playbooks/vars/sample-variables-sap-swpm-default-templates-mode.yml
collection: prepare for v1.3.1
> collection: prepare for v1.3.1

- roles/sap_swpm/tasks/post_install.yml
- Append checks for hdbuserstore existing on the host
> sap_swpm: hdbuserstore check

- roles/sap_install_media_detect/tasks/find_files_after_extraction.yml
- roles/sap_install_media_detect/tasks/prepare/create_file_list_phase_2.yml
- roles/sap_install_media_detect/tasks/set_global_vars.yml
> sap_install_media_detect: Handle db and db client separately

- roles/sap_install_media_detect/tasks/main.yml
- roles/sap_install_media_detect/tasks/prepare/enable_rar_handling.yml
- Install `unar` package when using SLES4SAP
> sap_install_media_detect: unar for sles

- roles/sap_general_preconfigure/vars/RedHat_9.yml
- roles/sap_hana_preconfigure/vars/RedHat_9.yml
> sap*preconfigure: Install package libxcrypt-compat on RHEL 9.x

- roles/sap_install_media_detect/defaults/main.yml
- roles/sap_install_media_detect/files/tmp/sapfile
- roles/sap_install_media_detect/tasks/find_files_after_extraction.yml
- roles/sap_install_media_detect/tasks/organize_files.yml
- roles/sap_install_media_detect/tasks/prepare/create_file_list_phase_2.yml
- roles/sap_install_media_detect/tasks/set_global_vars.yml
> sap_install_media_detect: Also recognize MP Stack XML files and correctly handle VCH AFL files

- roles/sap_general_preconfigure/tasks/RedHat/generic/configure-selinux.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/configure-selinux.yml
Also fix the `ansible-lint` `jinja[spacing]` violation next to the `ternary` filter (remove space character before the open parenthesis)
> Fix issue #479

- CHANGELOG.rst
- galaxy.yml
collection: prepare for v1.3.2
> collection: prepare for v1.3.2

- roles/sap_hana_preconfigure/vars/RedHat_8.yml
> sap_hana_preconfigure: Add RHEL 8.8 kernel version

- roles/sap_install_media_detect/files/tmp/sapfile
- roles/sap_install_media_detect/tasks/organize_files.yml
Partially fixes issue #519, to ensure that the directory sap_swpm will be created when needed.
> sap_install_media_detect: Ensure creation of directory sap_swpm

- roles/sap_ha_pacemaker_cluster/defaults/main.yml
- roles/sap_ha_pacemaker_cluster/meta/argument_specs.yml
- roles/sap_ha_pacemaker_cluster/tasks/configure_nwas_ascs_ers_postinstallation.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_haproxy_constraints_hana.yml
- roles/sap_ha_pacemaker_cluster/tasks/construct_vars_nwas_abap_ascs_ers.yml
- roles/sap_ha_pacemaker_cluster/tasks/include_construct_vip_resources.yml
- roles/sap_ha_pacemaker_cluster/tasks/main.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/construct_vars_vip_resources_cloud_ibmcloud_powervs.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/construct_vars_vip_resources_cloud_ibmcloud_vs.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/include_vars_platform.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/preconfigure_cloud_ibmcloud_vs.yml
- roles/sap_ha_pacemaker_cluster/tasks/platform/register_sysinfo_cloud_ibmcloud_powervs.yml
- roles/sap_ha_pacemaker_cluster/tasks/validate_input_parameters.yml
- roles/sap_ha_pacemaker_cluster/vars/main.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_ibmcloud_powervs.yml
- roles/sap_ha_pacemaker_cluster/vars/platform_cloud_ibmcloud_vs.yml
Merge with `dev` for end-to-end integration testing.
> sap_ha_pacemaker_cluster: add IBM Cloud VS platform functionality

- roles/sap_hana_install/tasks/hana_addhosts.yml
- roles/sap_hana_install/tasks/hana_exists.yml
Solves issue https://github.com/sap-linuxlab/community.sap_install/issues/556 for this role.
> sap_hana_install: Support Ansible 2.16.1

- roles/sap_hana_preconfigure/tasks/RedHat/assert-installation.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-2055470-loop-block.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-2382421-loop-block.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-2777782-01-loop-block.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-3024346-loop-block.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-abrt-ccpp.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-abrtd.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-auto-numa-balancing.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-coredumps.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-firewalld.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-kdump.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-ksm.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-services.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-tuned.yml
- roles/sap_hana_preconfigure/tasks/RedHat/installation.yml
- roles/sap_hana_preconfigure/tasks/SLES/assert-configuration.yml
- roles/sap_hana_preconfigure/tasks/sapnote/assert-2009879_7.yml
- roles/sap_hana_preconfigure/tasks/sapnote/assert-2382421.yml
- roles/sap_hana_preconfigure/tasks/sapnote/assert-3024346.yml
Solves issue https://github.com/sap-linuxlab/community.sap_install/issues/556 for this role.
> sap_hana_preconfigure: Support Ansible 2.16.1 

- roles/sap_netweaver_preconfigure/tasks/RedHat/assert-configuration.yml
- roles/sap_netweaver_preconfigure/tasks/RedHat/assert-installation.yml
- roles/sap_netweaver_preconfigure/tasks/SLES/assert-configuration.yml
- roles/sap_netweaver_preconfigure/tasks/SLES/assert-installation.yml
- roles/sap_netweaver_preconfigure/tasks/sapnote/assert-2526952.yml
Solves issue https://github.com/sap-linuxlab/community.sap_install/issues/556 for this role.
> sap_netweaver_preconfigure: Support Ansible 2.16.1

- .github/workflows/codespell.yml
Use [codespell](https://github.com/codespell-project/actions-codespell) for spell checking code in PRs and pushes to main.
> Add codespell GitHub actions workflow

- roles/sap_general_preconfigure/README.md
- roles/sap_hana_preconfigure/README.md
- roles/sap_netweaver_preconfigure/README.md
> sap*preconfigure: Update README.md files with RHEL 9 information

- .github/workflows/ansible-lint-sap_install_media_detect.yml
Solves issue #575 for this role.
> sap_install_media_detect: Add ansible-lint workflow

- .github/workflows/ansible-lint-sap_maintain_etc_hosts.yml
Solves issue #575 for this role.
> sap_maintain_etc_hosts: Add ansible-lint workflow

- roles/sap_maintain_etc_hosts/tasks/main.yml
Also fix a typo in two assert messages.
> sap_maintain_etc_hosts: Add support for Ansible 2.16.1

- roles/sap_swpm/tasks/swpm.yml
This is fix for issue #547 to remove cross repository dependency.
> sap_swpm: issue #547 python3-pip dependency

- roles/sap_hana_preconfigure/defaults/main.yml
- roles/sap_hana_preconfigure/tasks/SLES/assert-configuration.yml
- roles/sap_hana_preconfigure/tasks/SLES/assert-installation.yml
- roles/sap_hana_preconfigure/tasks/SLES/configuration.yml
- roles/sap_hana_preconfigure/tasks/SLES/installation.yml
- roles/sap_hana_preconfigure/vars/main.yml
- roles/sap_netweaver_preconfigure/defaults/main.yml
- roles/sap_netweaver_preconfigure/tasks/SLES/assert-configuration.yml
- roles/sap_netweaver_preconfigure/tasks/SLES/configuration.yml
- roles/sap_netweaver_preconfigure/tasks/SLES/installation.yml
sap*preconfigure: linting fixes
Address ansible-lint errors from PR #537 for Issue #499
> sap*preconfigure: linting fixes

- roles/sap_hypervisor_node_preconfigure/tasks/platform/redhat_rhel_kvm/assert-installation.yml
> sap_hypervisor_node_preconfigure: Fix leftover 'that:' statement

- .github/workflows/ansible-lint-sap_vm_preconfigure.yml
> sap_vm_preconfigure: Bump version of ansible-lint to 6.22.1

- docs/README.md
> collection: markdown url typo

- roles/sap_ha_pacemaker_cluster/tasks/import_hacluster_vars_from_inventory.yml
> fix(sap_ha_pacemaker_cluster): update with new condition

- roles/sap_ha_pacemaker_cluster/tasks/import_hacluster_vars_from_inventory.yml
This reverts commit 2a8359425c2b991f193065cf71eacdd9e696c683, reversing changes made to 5ee5cbe030ad152edfe96567155812f9abcdc25f.
> Revert "Merge pull request #616 from Wabri/feature/615/pacemaker"

- galaxy.yml
> collection: Use license_file in galaxy.yml

- .github/workflows/ansible-lint-sap_reusable_workflow.yml
Relates to: #621. Maybe even fixes it ;-)
> fix(ansible-lint-sap_reusable_workflow): Add missing file to main branch

- .github/workflows/ansible-lint-sap_general_preconfigure.yml
- .github/workflows/ansible-lint-sap_ha_install_hana_hsr.yml
- .github/workflows/ansible-lint-sap_ha_pacemaker_cluster.yml
- .github/workflows/ansible-lint-sap_hana_install.yml
- .github/workflows/ansible-lint-sap_hana_preconfigure.yml
- .github/workflows/ansible-lint-sap_hypervisor_node_preconfigure.yml
- .github/workflows/ansible-lint-sap_install_media_detect.yml
- .github/workflows/ansible-lint-sap_maintain_etc_hosts.yml
- .github/workflows/ansible-lint-sap_netweaver_preconfigure.yml
- .github/workflows/ansible-lint-sap_storage_setup.yml
- .github/workflows/ansible-lint-sap_swpm.yml
- .github/workflows/ansible-lint-sap_vm_preconfigure.yml
Solves issue #621 (hopefully).
The workflows are now also watching a branch named "github-workflow-test". If such a branch exists, a workflow will be triggered if there is a change to a file of the role in this branch. Can be useful for testing.
See also https://github.com/berndfinger/community.sap_install/actions/runs/7671935703/job/20911364277 .
> collection/workflow: Fix workflow issues

- roles/sap_anydb_install_oracle/tasks/oracledb_installer_minimal.yml
> sap_anydb_install_oracle: fix hardcoded oraInventory path and replace export with setenv

- roles/sap_anydb_install_oracle/defaults/main.yml
- roles/sap_anydb_install_oracle/tasks/main.yml
- roles/sap_anydb_install_oracle/tasks/oracledb_install_post_mopatch.yml
> sap_anydb_install_oracle: Add code for Oracle patches

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
collection: prepare for v1.4.0
> collection: prepare for v1.4.0

- roles/sap_general_preconfigure/tasks/RedHat/generic/configure-selinux.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/configure-selinux.yml
> sap_hana_preconfigure: Catch SELinux disabled

- roles/sap_general_preconfigure/tests/run-sap_general_preconfigure-tests.py
- roles/sap_general_preconfigure/tools/beautify-assert-output.sh
- roles/sap_hana_install/files/tmp/tail-f-hdblcm-install-trc.sh
- roles/sap_hana_install/tests/install/run-sap_hana_install-install-tests.py
- roles/sap_hana_install/tests/sapcar/run-sap_hana_install-sapcar-tests.py
- roles/sap_hana_preconfigure/tools/beautify-assert-output.sh
- roles/sap_install_media_detect/files/tmp/sapfile
- roles/sap_netweaver_preconfigure/tools/beautify-assert-output.sh
> collection: Fix ansible-test sanity errors

- .github/workflows/ansible-lint-sap_general_preconfigure.yml
- .github/workflows/ansible-lint-sap_ha_install_hana_hsr.yml
- .github/workflows/ansible-lint-sap_ha_pacemaker_cluster.yml
- .github/workflows/ansible-lint-sap_hana_install.yml
- .github/workflows/ansible-lint-sap_hana_preconfigure.yml
- .github/workflows/ansible-lint-sap_install_media_detect.yml
- .github/workflows/ansible-lint-sap_maintain_etc_hosts.yml
- .github/workflows/ansible-lint-sap_netweaver_preconfigure.yml
- .github/workflows/ansible-lint-sap_storage_setup.yml
- .github/workflows/ansible-lint-sap_swpm.yml
> fix(.github/workflows): remove github-workflow-test branch

- roles/sap_hana_preconfigure/handlers/main.yml
- roles/sap_hana_preconfigure/tasks/SLES/configuration.yml
> fix(sap_hana_preconfigure): move handlers to the correct location

- playbooks/sample-sap-swpm-default-mode.yml
- playbooks/vars/sample-variables-sap-swpm-default-mode-s4hana-distributed-aas-install.yml
> collection: Added a sample AAS installation var file and a link to it from onehost playbook

- workflows/check_outdate_deps/check_deps.py
> Workflow:fix sanity check

- workflows/check_outdate_deps/check_deps.py
The automation works, but I didn't consider that the stash can produce conflicts. With this changes all the conflicts in the requirements file are resolved by always taking the new changes.
Once this pr will be merge and the action run again, the conflicts will be mark as solved.
***I've also added the date of the commit in the description***
> Workflow: always accept the new changes

- roles/sap_swpm/tasks/swpm.yml
[Issue #738](https://github.com/sap-linuxlab/community.sap_install/issues/738)
> Aligned the SWPM execution and monitoring timeouts to 24hrs (86400s)

- roles/sap_general_preconfigure/tasks/RedHat/generic/assert-etc-hosts.yml
Solves issue #736.
It's essentially a backout of PR #697, especially of commit 1fc1459.
> sap_general_preconfigure: Revert to awk for asserting /etc/hosts

- roles/sap_general_preconfigure/tasks/main.yml
- roles/sap_ha_pacemaker_cluster/tasks/Suse/pre_steps_hana.yml
- roles/sap_ha_pacemaker_cluster/tasks/include_construct_vip_resources.yml
- roles/sap_hana_preconfigure/tasks/main.yml
- roles/sap_netweaver_preconfigure/tasks/main.yml
- roles/sap_swpm/tasks/pre_install/firewall.yml
sap_*: add python3-rpm for sles to resolve package_facts error in GH Issue #649
> sap_*: add python3-rpm for sles

- roles/sap_install_media_detect/tasks/prepare/move_files_to_main_directory.yml
- roles/sap_swpm/defaults/main.yml
- roles/sap_swpm/tasks/swpm/swpm_pre_install.yml
sap_swpm and sap_install_media_detect: sap_swpm dir handling
- Append separate var for extraction in `sap_swpm` Ansible Role
- Search for existing `sap_swpm` directory in `sap_install_media_detect` Ansible Role
> sap_swpm and sap_install_media_detect: sap_swpm dir handling

- roles/sap_install_media_detect/tasks/find_files_after_extraction.yml
- roles/sap_install_media_detect/tasks/prepare/create_file_list_phase_2.yml
- roles/sap_install_media_detect/tasks/set_global_vars.yml
> sap_install_media_detect: Allow detection of SAPEXE only

- .github/workflows/codespell.yml
- workflows/check_outdate_deps/action.yml
> Workflows: Add missing '---'

- roles/sap_swpm/tasks/swpm/prepare_software.yml
> sap_swpm: No longer change mode and user of files in extracted dirs

- roles/sap_install_media_detect/tasks/prepare/create_file_list_phase_1.yml
- roles/sap_install_media_detect/tasks/prepare/create_file_list_phase_2.yml
- roles/sap_install_media_detect/tasks/prepare/move_files_to_main_directory.yml
sap_install_media_detect: append loop labels to address GH Issue #780
> sap_install_media_detect: append loop labels

- roles/sap_hana_preconfigure/vars/RedHat_9.yml
> sap_hana_preconfigure: Add RHEL 9.4 requirements

- roles/sap_swpm/defaults/main.yml
Add default value for sap_swpm_java_scs_instance_hostname
> sap_swpm: Add default value for sap_swpm_java_scs_instance_hostname

- roles/sap_hana_preconfigure/README.md
- roles/sap_hana_preconfigure/meta/argument_specs.yml
> refactor(sap_hana_preconfigure): remove default saptune version

- .yamllint.yml
- roles/sap_anydb_install_oracle/.yamllint.yml
- roles/sap_general_preconfigure/.yamllint.yml
- roles/sap_ha_install_anydb_ibmdb2/.yamllint.yml
- roles/sap_ha_install_hana_hsr/.yamllint.yml
- roles/sap_ha_pacemaker_cluster/.yamllint.yml
- roles/sap_hana_install/.yamllint.yml
- roles/sap_hana_preconfigure/.yamllint.yml
- roles/sap_hostagent/.yamllint.yml
- roles/sap_install_media_detect/.yamllint.yml
- roles/sap_maintain_etc_hosts/.yamllint.yml
- roles/sap_netweaver_preconfigure/.yamllint.yml
- roles/sap_storage_setup/.yamllint.yml
- roles/sap_swpm/.yamllint.yml
Solves issue #823.
Relates to https://github.com/sap-linuxlab/community.sap_install/issues/810 and https://github.com/sap-linuxlab/community.sap_install/pull/811.
> collection: Synchronize all .yamllint.yml files

- roles/sap_install_media_detect/defaults/main.yml
- roles/sap_install_media_detect/tasks/main.yml
- roles/sap_install_media_detect/tasks/prepare/create_file_list_phase_2.yml
> sap_install_media_detect: Allow disabling RAR handling

- playbooks/sap_hana_preconfigure_exec.yml
> Some tweaks for sample playbook sap hana preconfigure exec.yml

- requirements.yml
> collection: Specify minimum version for dependent collections

- roles/sap_hana_preconfigure/README.md
- roles/sap_hana_preconfigure/defaults/main.yml
- roles/sap_hana_preconfigure/handlers/main.yml
- roles/sap_hana_preconfigure/meta/argument_specs.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/assert-thp.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/configure-thp.yml
> sap_hana_preconfigure: Allow setting THP to any possible value

- roles/sap_swpm/tasks/pre_install/swpm_prepare.yml
> sap_swpm: Add tag to sap_swpm_tmpdir task

- roles/sap_general_preconfigure/tasks/RedHat/generic/configure-kernel-parameters.yml
> sap_general_preconfigure: Fix check mode for sysctl

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
collection: gh issue templates
> collection: gh issue templates

- roles/sap_general_preconfigure/vars/RedHat_10.yml
> sap_general_preconfigure: Update the package name of the IBM Power tools for RHEL 10

- roles/sap_general_preconfigure/tasks/RedHat/generic/configure-selinux.yml
- roles/sap_hana_preconfigure/tasks/RedHat/generic/configure-selinux.yml
> sap*preconfigure: Make SELinux booleans persistent

- roles/sap_anydb_install_oracle/tasks/main.yml
- roles/sap_anydb_install_oracle/tasks/oracledb_install_pre.yml
- roles/sap_anydb_install_oracle/vars/RedHat.yml
- roles/sap_anydb_install_oracle/vars/Suse.yml
- Added loading of OS specific variables based on ansible distribution and versions, similar to existing one used in other roles.
- Corrected packages for SUSE as existing list was not valid.
> sap_anydb_install_oracle: Add handling of OS specific vars

- roles/sap_general_preconfigure/tasks/RedHat/assert-installation.yml
- roles/sap_hana_preconfigure/tasks/RedHat/assert-installation.yml
> sap_*_preconfigure: Define needs-restarting also for RHEL 10, assert mode

- roles/sap_install_media_detect/files/tmp/sapfile
> sap_install_media_detect: correctly detect sap_export_nwas_java
